import { Appointment, WorkshopBay } from "@/domains/calendar/types";

export const initialBaysData: WorkshopBay[] = [
  {
    id: "bay-1",
    organizationId: "org-xmotion-1",
    name: "Baia 1 — PPF Master & Precision",
    code: "B1-PPF",
    serviceType: "ppf",
    defaultTechnicianName: "João Martins",
    status: "occupied",
  },
  {
    id: "bay-2",
    organizationId: "org-xmotion-1",
    name: "Baia 2 — Wrap & Prep",
    code: "B2-WRAP",
    serviceType: "wrap",
    defaultTechnicianName: "Rui Almeida",
    status: "occupied",
  },
  {
    id: "bay-3",
    organizationId: "org-xmotion-1",
    name: "Baia 3 — Frontal PPF & Detailing",
    code: "B3-FRONT",
    serviceType: "ppf",
    defaultTechnicianName: "Pedro Santos",
    status: "occupied",
  },
  {
    id: "bay-4",
    organizationId: "org-xmotion-1",
    name: "Baia 4 — Chrome Delete & Acabamentos",
    code: "B4-FINISH",
    serviceType: "general",
    defaultTechnicianName: "Miguel Costa",
    status: "occupied",
  },
];

export const initialAppointmentsData: Appointment[] = [
  {
    id: "app-1",
    organizationId: "org-xmotion-1",
    quoteId: "quote-1",
    quoteNumber: "ORC-2026-042",
    vehicleId: "veh-1",
    vehiclePlate: "44-TX-88",
    vehicleModel: "BMW M4 Competition Coupe",
    customerId: "c-b2b-1",
    customerName: "AutoStand Prime Barcelos",
    bayId: "bay-1",
    bayName: "Baia 1 — PPF Master",
    technicianName: "João Martins",
    serviceTitle: "PPF Completo Auto-regenerativo",
    startTime: "09:00",
    endTime: "18:00",
    date: "2026-08-28",
    estimatedHours: 8.5,
    status: "in_progress",
    notes: "Viatura com check-in concluído. Em fase de aplicação de portas.",
  },
  {
    id: "app-2",
    organizationId: "org-xmotion-1",
    quoteId: "quote-2",
    quoteNumber: "ORC-2026-040",
    vehicleId: "veh-2",
    vehiclePlate: "99-PZ-11",
    vehicleModel: "Porsche 911 Carrera 4S (992)",
    customerId: "c-part-1",
    customerName: "Bernardo Silva",
    bayId: "bay-2",
    bayName: "Baia 2 — Wrap & Prep",
    technicianName: "Rui Almeida",
    serviceTitle: "Full Body Wrap Satin Grey",
    startTime: "10:00",
    endTime: "19:00",
    date: "2026-08-28",
    estimatedHours: 7.5,
    status: "in_progress",
    notes: "Desmontagem concluída e wrap das laterais em curso.",
  },
  {
    id: "app-3",
    organizationId: "org-xmotion-1",
    quoteId: "quote-5",
    quoteNumber: "ORC-2026-039",
    vehicleId: "veh-3",
    vehiclePlate: "12-RS-66",
    vehicleModel: "Audi RS6 Avant V8 BiTurbo",
    customerId: "c-part-3",
    customerName: "Tiago Cerqueira",
    bayId: "bay-3",
    bayName: "Baia 3 — Frontal PPF",
    technicianName: "Pedro Santos",
    serviceTitle: "PPF Frontal Completo & Cerâmica",
    startTime: "12:00",
    endTime: "18:00",
    date: "2026-08-28",
    estimatedHours: 6.0,
    status: "in_progress",
    notes: "Capô e para-choques concluídos. Em cura térmica.",
  },
  {
    id: "app-4",
    organizationId: "org-xmotion-1",
    vehicleId: "veh-4",
    vehiclePlate: "78-MB-22",
    vehicleModel: "Mercedes GLC Coupe 300d",
    customerId: "c-part-2",
    customerName: "Miguel Ângelo Costa",
    bayId: "bay-4",
    bayName: "Baia 4 — Chrome Delete",
    technicianName: "Miguel Costa",
    serviceTitle: "Chrome Delete Integral",
    startTime: "14:00",
    endTime: "17:30",
    date: "2026-08-28",
    estimatedHours: 4.0,
    status: "in_progress",
    notes: "A aguardar fitas especiais de recorte para difusor.",
  },
  {
    id: "app-5",
    organizationId: "org-xmotion-1",
    vehicleId: "veh-5",
    vehiclePlate: "33-TS-99",
    vehicleModel: "Tesla Model 3 Long Range",
    customerId: "c-part-4",
    customerName: "Ana Rita Ferreira",
    bayId: "bay-3",
    bayName: "Baia 3 — Detailing",
    technicianName: "Ana Ferreira",
    serviceTitle: "Detailing Interior & Proteção de Ecrã",
    startTime: "16:00",
    endTime: "18:30",
    date: "2026-08-28",
    estimatedHours: 2.5,
    status: "scheduled",
    notes: "Chegada prevista às 16:00 para check-in rápido.",
  },
  {
    id: "app-6",
    organizationId: "org-xmotion-1",
    vehicleId: "veh-6",
    vehiclePlate: "48-FE-88",
    vehicleModel: "Ferrari 488 GTB",
    customerId: "c-part-6",
    customerName: "Duarte Faria",
    bayId: "bay-1",
    bayName: "Baia 1 — PPF Master",
    technicianName: "João Martins",
    serviceTitle: "Entrega Final & Certificado de Garantia",
    startTime: "17:30",
    endTime: "18:00",
    date: "2026-08-28",
    estimatedHours: 1.0,
    status: "scheduled",
    notes: "Viatura pronta e limpa. Entrega agendada para as 17:30.",
  },
];
