import { Checkin } from "@/domains/checkins/types";

export const initialCheckinsData: Checkin[] = [
  {
    id: "chk-1",
    organizationId: "org-xmotion-1",
    appointmentId: "app-1",
    quoteId: "quote-1",
    vehicleId: "veh-1",
    vehiclePlate: "44-TX-88",
    vehicleModel: "BMW M4 Competition Coupe",
    vehicleYear: 2024,
    vehicleColor: "Isle of Man Green Metallic",
    customerId: "c-b2b-1",
    customerName: "AutoStand Prime Barcelos",
    customerPhone: "+351 912 345 678",
    type: "entry",
    mileage: 14250,
    fuelLevel: "three_quarters",
    hasRoofPhoto: true, // REGRA DO TEJADILHO CUMPRIDA
    cleanlinessStatus: "clean",
    technicianName: "João Martins",
    signedByName: "Carlos Antunes (AutoStand)",
    status: "completed",
    token: "tok-chk-44tx88-2026",
    createdAt: "2026-08-28 09:15",
    completedAt: "2026-08-28 09:30",
    damages: [
      {
        id: "dmg-1",
        posX: 22,
        posY: 35,
        bodyPart: "Para-choques Frontal (Lado Direito)",
        type: "stone_chip",
        severity: "minor",
        notes: "Duas micro picadas de gravilha perto da grelha inferior.",
      },
      {
        id: "dmg-2",
        posX: 74,
        posY: 68,
        bodyPart: "Jante Traseira Direita",
        type: "scratch",
        severity: "minor",
        notes: "Pequeno toque de passeio superficial na borda da jante.",
      },
    ],
    photos: [
      {
        id: "cp-1-1",
        photoUrl: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&auto=format&fit=crop&q=60",
        angle: "front",
        label: "Frente",
        isMandatory: true,
        createdAt: "2026-08-28 09:20",
      },
      {
        id: "cp-1-2",
        photoUrl: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&auto=format&fit=crop&q=60",
        angle: "left_side",
        label: "Lateral Esquerdo",
        isMandatory: true,
        createdAt: "2026-08-28 09:21",
      },
      {
        id: "cp-1-3",
        photoUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=60",
        angle: "right_side",
        label: "Lateral Direito",
        isMandatory: true,
        createdAt: "2026-08-28 09:22",
      },
      {
        id: "cp-1-4",
        photoUrl: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&auto=format&fit=crop&q=60",
        angle: "rear",
        label: "Traseira",
        isMandatory: true,
        createdAt: "2026-08-28 09:23",
      },
      {
        id: "cp-1-5",
        photoUrl: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop&q=60",
        angle: "roof",
        label: "Tejadilho",
        isMandatory: true,
        createdAt: "2026-08-28 09:24",
      },
      {
        id: "cp-1-6",
        photoUrl: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=800&auto=format&fit=crop&q=60",
        angle: "odometer",
        label: "Odómetro (14.250 km)",
        isMandatory: true,
        createdAt: "2026-08-28 09:25",
      },
    ],
    belongings: [
      { id: "bel-1", itemName: "Chave da Viatura", isPresent: true, notes: "Chave inteligente BMW" },
      { id: "bel-2", itemName: "Perno de Segurança de Jantes", isPresent: true, notes: "Na mala" },
      { id: "bel-3", itemName: "Documento Único Automóvel (DUA)", isPresent: true, notes: "No porta-luvas" },
      { id: "bel-4", itemName: "Objetos de Valor Pessoais", isPresent: false, notes: "Viatura entregue sem objetos pessoais" },
    ],
  },
  {
    id: "chk-2",
    organizationId: "org-xmotion-1",
    appointmentId: "app-2",
    quoteId: "quote-2",
    vehicleId: "veh-2",
    vehiclePlate: "99-PZ-11",
    vehicleModel: "Porsche 911 Carrera 4S (992)",
    vehicleYear: 2023,
    vehicleColor: "GT Silver Metallic",
    customerId: "c-part-1",
    customerName: "Bernardo Silva",
    customerPhone: "+351 925 111 222",
    type: "entry",
    mileage: 28400,
    fuelLevel: "full",
    hasRoofPhoto: true, // REGRA DO TEJADILHO CUMPRIDA
    cleanlinessStatus: "clean",
    technicianName: "João Martins",
    signedByName: "Bernardo Silva",
    status: "completed",
    token: "tok-chk-99pz11-2026",
    createdAt: "2026-08-28 10:10",
    completedAt: "2026-08-28 10:25",
    damages: [
      {
        id: "dmg-3",
        posX: 50,
        posY: 15,
        bodyPart: "Capô Central",
        type: "stone_chip",
        severity: "minor",
        notes: "Picada leve de autoestrada.",
      },
    ],
    photos: [
      {
        id: "cp-2-1",
        photoUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=60",
        angle: "front",
        label: "Frente",
        isMandatory: true,
        createdAt: "2026-08-28 10:15",
      },
      {
        id: "cp-2-2",
        photoUrl: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&auto=format&fit=crop&q=60",
        angle: "left_side",
        label: "Lateral Esquerdo",
        isMandatory: true,
        createdAt: "2026-08-28 10:16",
      },
      {
        id: "cp-2-3",
        photoUrl: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&auto=format&fit=crop&q=60",
        angle: "roof",
        label: "Tejadilho",
        isMandatory: true,
        createdAt: "2026-08-28 10:17",
      },
    ],
    belongings: [
      { id: "bel-5", itemName: "Chave da Viatura", isPresent: true, notes: "Chave Porsche cinza" },
      { id: "bel-6", itemName: "Perno de Segurança de Jantes", isPresent: true },
      { id: "bel-7", itemName: "Documentos", isPresent: true },
    ],
  },
  {
    id: "chk-3",
    organizationId: "org-xmotion-1",
    appointmentId: "app-3",
    quoteId: "quote-5",
    vehicleId: "veh-3",
    vehiclePlate: "12-RS-66",
    vehicleModel: "Audi RS6 Avant V8 BiTurbo",
    vehicleYear: 2021,
    vehicleColor: "Nardo Grey",
    customerId: "c-part-3",
    customerName: "Tiago Cerqueira",
    customerPhone: "+351 917 888 999",
    type: "entry",
    mileage: 62100,
    fuelLevel: "half",
    hasRoofPhoto: true, // REGRA DO TEJADILHO CUMPRIDA
    cleanlinessStatus: "clean",
    technicianName: "Pedro Santos",
    signedByName: "Tiago Cerqueira",
    status: "completed",
    token: "tok-chk-12rs66-2026",
    createdAt: "2026-08-28 12:05",
    completedAt: "2026-08-28 12:20",
    damages: [],
    photos: [
      {
        id: "cp-3-1",
        photoUrl: "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&auto=format&fit=crop&q=60",
        angle: "front",
        label: "Frente",
        isMandatory: true,
        createdAt: "2026-08-28 12:10",
      },
      {
        id: "cp-3-2",
        photoUrl: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=800&auto=format&fit=crop&q=60",
        angle: "odometer",
        label: "Odómetro (62.100 km)",
        isMandatory: true,
        createdAt: "2026-08-28 12:11",
      },
      {
        id: "cp-3-3",
        photoUrl: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop&q=60",
        angle: "roof",
        label: "Tejadilho",
        isMandatory: true,
        createdAt: "2026-08-28 12:12",
      },
    ],
    belongings: [
      { id: "bel-8", itemName: "Chave da Viatura", isPresent: true },
      { id: "bel-9", itemName: "Perno de Segurança de Jantes", isPresent: true },
    ],
  },
];
