import {
  Invoice,
  Delivery,
  WarrantyCertificate,
  PassportFullRecord,
} from "@/domains/finance/types";

export const initialInvoicesData: Invoice[] = [
  {
    id: "inv-1",
    invoiceNumber: "FT 2026/042",
    workOrderId: "wo-1",
    quoteId: "q-1",
    customerId: "cust-1",
    customerName: "AutoStand Prime Barcelos",
    customerNif: "PT509887766",
    customerAddress: "Avenida dos Automóveis, 450, Barcelos",
    vehiclePlate: "44-TX-88",
    vehicleModel: "BMW M4 Competition Coupe (2024)",
    subtotal: 4000.0,
    vatRate: 23.0,
    vatAmount: 920.0,
    totalAmount: 4920.0,
    paymentMethod: "bank_transfer",
    paymentStatus: "paid",
    issuedAt: "2026-08-28 17:00",
    dueAt: "2026-08-28",
    paidAt: "2026-08-28 17:15",
    lines: [
      {
        id: "inl-1",
        description: "Aplicação Integral de PPF Stek DYNOshield Gloss Auto-regenerativo",
        quantity: 1,
        unitPrice: 3600.0,
        vatRate: 23.0,
        lineTotal: 3600.0,
      },
      {
        id: "inl-2",
        description: "Descontaminação Química/Mecânica & Desmontagem Técnica",
        quantity: 1,
        unitPrice: 400.0,
        vatRate: 23.0,
        lineTotal: 400.0,
      },
    ],
  },
  {
    id: "inv-2",
    invoiceNumber: "FT 2026/040",
    workOrderId: "wo-2",
    quoteId: "q-2",
    customerId: "cust-3",
    customerName: "Bernardo Silva",
    customerNif: "PT234567890",
    vehiclePlate: "99-PZ-11",
    vehicleModel: "Porsche 911 Carrera 4S (992)",
    subtotal: 2800.0,
    vatRate: 23.0,
    vatAmount: 644.0,
    totalAmount: 3444.0,
    paymentMethod: "mbway",
    paymentStatus: "paid",
    issuedAt: "2026-08-28 15:00",
    dueAt: "2026-08-28",
    paidAt: "2026-08-28 15:10",
    lines: [
      {
        id: "inl-3",
        description: "Full Body Wrap Vinil 3M 2080 Satin Dark Grey",
        quantity: 1,
        unitPrice: 2800.0,
        vatRate: 23.0,
        lineTotal: 2800.0,
      },
    ],
  },
  {
    id: "inv-3",
    invoiceNumber: "FT 2026/039",
    workOrderId: "wo-3",
    quoteId: "q-3",
    customerId: "cust-2",
    customerName: "Tiago Cerqueira",
    customerNif: "PT198765432",
    vehiclePlate: "12-RS-66",
    vehicleModel: "Audi RS6 Avant V8 BiTurbo",
    subtotal: 2200.0,
    vatRate: 23.0,
    vatAmount: 506.0,
    totalAmount: 2706.0,
    paymentMethod: "bank_transfer",
    paymentStatus: "paid",
    issuedAt: "2026-08-27 18:00",
    dueAt: "2026-08-27",
    paidAt: "2026-08-27 18:30",
    lines: [
      {
        id: "inl-4",
        description: "PPF Frontal Completo Stek DYNOshield & Cerâmica de Jantes",
        quantity: 1,
        unitPrice: 2200.0,
        vatRate: 23.0,
        lineTotal: 2200.0,
      },
    ],
  },
];

export const initialDeliveriesData: Delivery[] = [
  {
    id: "del-1",
    workOrderId: "wo-1",
    vehiclePlate: "44-TX-88",
    vehicleModel: "BMW M4 Competition Coupe",
    customerId: "cust-1",
    customerName: "AutoStand Prime Barcelos",
    deliveredByName: "João Martins (Lead Detailer)",
    receiverName: "Miguel Ângelo Costa",
    receiverIdDocument: "CC 14882991-2",
    signatureDataUrl: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='60'><path d='M20 30 Q 80 10, 120 40 T 180 20' stroke='%23d3a548' fill='none' stroke-width='3'/></svg>",
    belongingsReturnedConfirmed: true,
    belongings: [
      {
        id: "bel-1",
        name: "Chave Principal BMW M c/ capa em pele",
        isReturned: true,
        returnedAt: "2026-08-28 17:30",
      },
      {
        id: "bel-2",
        name: "Comando de garagem AutoStand",
        isReturned: true,
        returnedAt: "2026-08-28 17:30",
      },
    ],
    notes: "Viatura entregue em estado irrepreensível, inspecionada conjuntamente sob luz natural. Cliente assinou levantamento e ativou garantia digital.",
    deliveredAt: "2026-08-28 17:30",
    token: "tok-del-44tx88-2026",
  },
];

export const initialWarrantiesData: WarrantyCertificate[] = [
  {
    id: "war-1",
    vehiclePlate: "44-TX-88",
    vehicleModel: "BMW M4 Competition Coupe",
    customerId: "cust-1",
    customerName: "AutoStand Prime Barcelos",
    workOrderId: "wo-1",
    materialName: "Stek DYNOshield Gloss Auto-regenerativo",
    batchNumber: "STEK-DS-2026-04",
    warrantyYears: 10,
    certificateNumber: "QC-2026-44TX88-PASS",
    qcCertificateNumber: "QC-2026-44TX88-PASS",
    termsText: "Garantia oficial de 10 anos contra descolamento de arestas, formação de bolhas, amarelecimento e perda de transparência da película Stek DYNOshield aplicada por centro autorizado X-Motion.",
    maintenanceRules: [
      {
        id: "mr-1",
        title: "Período de Cura Inicial (72 Horas)",
        description: "Não lave a viatura nem exponha a chuva torrencial nas primeiras 72 horas após a aplicação para garantir a polimerização total do gel de aderência.",
        isCritical: true,
      },
      {
        id: "mr-2",
        title: "Lavagem Segura com pH Neutro",
        description: "Utilize o método de lavagem de dois baldes com champô de pH neutro e luva de microfibras de alta gramagem. Evite produtos ácidos.",
        isCritical: false,
      },
      {
        id: "mr-3",
        title: "Lanças de Alta Pressão",
        description: "Mantenha o bocal da máquina de pressão a uma distância mínima de 40 cm e nunca aponte perpendicularmente diretamente contra os bordos e remates.",
        isCritical: true,
      },
      {
        id: "mr-4",
        title: "Propriedade Auto-regenerativa",
        description: "Micro-riscos e marcas de lavagem regeneram-se naturalmente com a exposição solar ou aplicação de água morna (50°C a 60°C).",
        isCritical: false,
      },
    ],
    startsAt: "2026-08-28",
    expiresAt: "2036-08-28",
    status: "active",
    token: "tok-war-44tx88-2026",
  },
];

export const initialBMWPassport: PassportFullRecord = {
  vehicleId: "veh-1",
  plate: "44-TX-88",
  make: "BMW",
  model: "M4 Competition Coupe",
  generationYear: 2024,
  bodyType: "coupe",
  colorName: "Isle of Man Green Metallic",
  vin: "WBA43AZ05PFP12984",
  currentMileage: 14250,
  ownerName: "AutoStand Prime Barcelos",
  ownerType: "business",
  photoUrl: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1200&q=80",
  events: [
    {
      id: "ev-1",
      date: "2026-08-28 09:15",
      type: "checkin",
      title: "1. Receção & Inspeção Fotográfica 360°",
      subtitle: "Regra do Tejadilho Validada · 14 250 km",
      description: "Entrada na oficina com registo fotográfico integral (incluindo vista superior do tejadilho) e mapeamento de 2 picadas de gravilha pré-existentes.",
      badgeText: "Tejadilho Válido",
      badgeVariant: "success",
      actorName: "João Martins",
      documentNumber: "CHK-44TX88",
      linkHref: "/checkins/report/tok-chk-44tx88-2026",
    },
    {
      id: "ev-2",
      date: "2026-08-28 09:25",
      type: "quote",
      title: "2. Orçamento Aprovado (3-Tier)",
      subtitle: "Pacote Signature PPF Completo",
      description: "Cliente aprovou o nível Signature com Stek DYNOshield Integral, revestimento cerâmico de jantes e tratamento hidrofóbico de vidros.",
      badgeText: "€4 920,00 c/ IVA",
      badgeVariant: "gold",
      actorName: "Luís (Consultor Técnico)",
      documentNumber: "ORC-2026-042",
      linkHref: "/quotes/public/tok-quote-bmw-m4-2026",
    },
    {
      id: "ev-3",
      date: "2026-08-28 15:45",
      type: "work_order",
      title: "3. Produção Técnica em 8 Fases",
      subtitle: "Aplicação de Película e Cura Térmica",
      description: "Descontaminação mecânica, corte de película em plotter, aplicação por painel e pós-aquecimento térmico a 90°C.",
      badgeText: "8 Fases Concluídas",
      badgeVariant: "default",
      actorName: "João Martins",
      documentNumber: "OT-2026-042",
      linkHref: "/production/wo-1",
    },
    {
      id: "ev-4",
      date: "2026-08-28 16:30",
      type: "qc_pass",
      title: "4. Controlo de Qualidade Rigoroso (QC Pass)",
      subtitle: "10/10 Pontos de Conformidade Aprovados",
      description: "Inspeção ótica sob lâmpada Scangrip a 30cm sem bolhas nem resíduos. Remates 100% selados e verificação de aperto de pernos.",
      badgeText: "QC Approved",
      badgeVariant: "success",
      actorName: "João Martins (Lead Detailer)",
      documentNumber: "QC-2026-44TX88-PASS",
      linkHref: "/qc/certificate/QC-2026-44TX88-PASS",
    },
    {
      id: "ev-5",
      date: "2026-08-28 17:00",
      type: "invoice",
      title: "5. Fatura Emitida & Liquidada",
      subtitle: "Fatura FT 2026/042 com IVA a 23%",
      description: "Documento fiscal emitido com número de contribuinte PT509887766 e pagamento liquidado por transferência bancária.",
      badgeText: "Pago · FT 2026/042",
      badgeVariant: "outline",
      actorName: "Administração X-Flow",
      documentNumber: "FT 2026/042",
      linkHref: "/invoices/inv-1",
    },
    {
      id: "ev-6",
      date: "2026-08-28 17:30",
      type: "delivery",
      title: "6. Levantamento da Viatura & Entrega Formal",
      subtitle: "Assinatura do Cliente & Pertences Devolvidos",
      description: "Viatura inspecionada conjuntamente pelo cliente. Chaves originais devolvidas e assinatura digital recolhida na tela.",
      badgeText: "Entregue",
      badgeVariant: "success",
      actorName: "Miguel Ângelo Costa (Cliente)",
      documentNumber: "DEL-44TX88",
      linkHref: "/deliveries/del-1",
    },
    {
      id: "ev-7",
      date: "2026-08-28 17:35",
      type: "warranty",
      title: "7. Garantia Digital de Fábrica Ativada",
      subtitle: "10 Anos de Cobertura Oficial Stek",
      description: "Ativação do certificado com número de lote STEK-DS-2026-04, válido até 28 de Agosto de 2036 com guia de manutenção.",
      badgeText: "10 Anos Ativa",
      badgeVariant: "gold",
      actorName: "X-Motion Performance Center",
      documentNumber: "WAR-44TX88",
      linkHref: "/warranties/certificate/tok-war-44tx88-2026",
    },
  ],
  activeWarranty: {
    materialName: "Stek DYNOshield Gloss",
    batchNumber: "STEK-DS-2026-04",
    warrantyYears: 10,
    expiresAt: "2036-08-28",
    certificateNumber: "QC-2026-44TX88-PASS",
  },
};
