import { Material } from "@/domains/materials/types";

export const initialMaterialsData: Material[] = [
  // 1. Stek DYNOshield Gloss
  {
    id: "mat-1",
    organizationId: "org-xmotion-1",
    brand: "Stek",
    name: "DYNOshield Gloss PPF",
    type: "ppf_gloss",
    thicknessMicrons: 200,
    finish: "Ultra Gloss",
    rollWidthMeters: 1.52,
    costPerMeter: 48,
    pricePerMeter: 120,
    currentStockMeters: 45.0,
    minimumStockAlertMeters: 20.0,
    unit: "meter",
    status: "available",
    supplierName: "Stek Europe Distribution",
    batches: [
      {
        id: "bat-1",
        organizationId: "org-xmotion-1",
        materialId: "mat-1",
        batchNumber: "STK-2026-04A",
        supplierName: "Stek Europe",
        receivedDate: "2026-08-01",
        initialMeters: 60,
        remainingMeters: 45,
      },
    ],
  },
  // 2. Stek DYNOmatte (CRITICAL STOCK - Low stock item 1)
  {
    id: "mat-2",
    organizationId: "org-xmotion-1",
    brand: "Stek",
    name: "DYNOmatte Satin PPF",
    type: "ppf_matte",
    thicknessMicrons: 200,
    finish: "Satin / Matte",
    rollWidthMeters: 1.52,
    costPerMeter: 54,
    pricePerMeter: 140,
    currentStockMeters: 6.5,
    minimumStockAlertMeters: 15.0,
    unit: "meter",
    status: "low_stock",
    supplierName: "Stek Europe Distribution",
    batches: [
      {
        id: "bat-2",
        organizationId: "org-xmotion-1",
        materialId: "mat-2",
        batchNumber: "STK-2026-03M",
        supplierName: "Stek Europe",
        receivedDate: "2026-07-15",
        initialMeters: 30,
        remainingMeters: 6.5,
      },
    ],
  },
  // 3. SunTek Reaction Gloss PPF
  {
    id: "mat-3",
    organizationId: "org-xmotion-1",
    brand: "SunTek",
    name: "Reaction High-Gloss PPF",
    type: "ppf_gloss",
    thicknessMicrons: 180,
    finish: "Gloss Ceramic Topcoat",
    rollWidthMeters: 1.52,
    costPerMeter: 44,
    pricePerMeter: 110,
    currentStockMeters: 32.0,
    minimumStockAlertMeters: 15.0,
    unit: "meter",
    status: "available",
    supplierName: "Eastman Performance Films",
  },
  // 4. Xpel Stealth Satin PPF (CRITICAL STOCK - Low stock item 2)
  {
    id: "mat-4",
    organizationId: "org-xmotion-1",
    brand: "Xpel",
    name: "STEALTH Satin PPF",
    type: "ppf_matte",
    thicknessMicrons: 200,
    finish: "Satin Matte",
    rollWidthMeters: 1.52,
    costPerMeter: 56,
    pricePerMeter: 145,
    currentStockMeters: 4.0,
    minimumStockAlertMeters: 15.0,
    unit: "meter",
    status: "low_stock",
    supplierName: "Xpel Continental",
  },
  // 5. Stek DYNOcarbon (CRITICAL STOCK - Low stock item 3)
  {
    id: "mat-5",
    organizationId: "org-xmotion-1",
    brand: "Stek",
    name: "DYNOcarbon Gloss Carbon PPF",
    type: "color_ppf",
    thicknessMicrons: 200,
    finish: "Carbon Fiber Texture",
    rollWidthMeters: 1.52,
    costPerMeter: 68,
    pricePerMeter: 175,
    currentStockMeters: 2.5,
    minimumStockAlertMeters: 10.0,
    unit: "meter",
    status: "low_stock",
    supplierName: "Stek Europe Distribution",
  },
  // 6. 3M 2080 Gloss Black Vinyl (CRITICAL STOCK - Low stock item 4)
  {
    id: "mat-6",
    organizationId: "org-xmotion-1",
    brand: "3M",
    name: "Series 2080 High Gloss Black Vinyl",
    type: "cast_vinyl",
    thicknessMicrons: 90,
    finish: "Gloss Black",
    rollWidthMeters: 1.52,
    costPerMeter: 24,
    pricePerMeter: 65,
    currentStockMeters: 5.0,
    minimumStockAlertMeters: 20.0,
    unit: "meter",
    status: "low_stock",
    supplierName: "Spandex Portugal",
  },
  // 7. Avery Dennison SWF Satin Black
  {
    id: "mat-7",
    organizationId: "org-xmotion-1",
    brand: "Avery Dennison",
    name: "Supreme Wrapping Film Satin Black",
    type: "cast_vinyl",
    thicknessMicrons: 80,
    finish: "Satin Black",
    rollWidthMeters: 1.52,
    costPerMeter: 22,
    pricePerMeter: 60,
    currentStockMeters: 28.0,
    minimumStockAlertMeters: 15.0,
    unit: "meter",
    status: "available",
    supplierName: "Spandex Portugal",
  },
  // 8. Gyeon Q2 Mohs EVO Ceramic (CRITICAL STOCK - Low stock item 5)
  {
    id: "mat-8",
    organizationId: "org-xmotion-1",
    brand: "Gyeon",
    name: "Q2 Mohs EVO Ceramic Coating 100ml",
    type: "ceramic",
    finish: "9H Glass Shield",
    rollWidthMeters: 0,
    costPerMeter: 85,
    pricePerMeter: 220,
    currentStockMeters: 1.0,
    minimumStockAlertMeters: 4.0,
    unit: "bottle",
    status: "low_stock",
    supplierName: "Detailing Power PT",
  },
  // 9. SunTek Ultra Defence 250u
  {
    id: "mat-9",
    organizationId: "org-xmotion-1",
    brand: "SunTek",
    name: "Ultra Defence High-Impact PPF (250µm)",
    type: "ppf_gloss",
    thicknessMicrons: 250,
    finish: "High Gloss",
    rollWidthMeters: 1.52,
    costPerMeter: 58,
    pricePerMeter: 150,
    currentStockMeters: 22.0,
    minimumStockAlertMeters: 10.0,
    unit: "meter",
    status: "available",
  },
  // 10. Stek DYNOshade Headlight Tint PPF
  {
    id: "mat-10",
    organizationId: "org-xmotion-1",
    brand: "Stek",
    name: "DYNOshade Light Smoke Tint PPF",
    type: "tint",
    thicknessMicrons: 150,
    finish: "Smoke Gloss",
    rollWidthMeters: 0.76,
    costPerMeter: 32,
    pricePerMeter: 85,
    currentStockMeters: 18.0,
    minimumStockAlertMeters: 10.0,
    unit: "meter",
    status: "available",
  },
  // 11. Xpel Fusion Plus Ceramic for PPF
  {
    id: "mat-11",
    organizationId: "org-xmotion-1",
    brand: "Xpel",
    name: "FUSION PLUS Ceramic Coating for PPF",
    type: "ceramic",
    finish: "Hydrophobic Gloss",
    rollWidthMeters: 0,
    costPerMeter: 90,
    pricePerMeter: 240,
    currentStockMeters: 6.0,
    minimumStockAlertMeters: 3.0,
    unit: "bottle",
    status: "available",
  },
  // 12. Avery Supreme Wrapping Gloss Nardo Grey
  {
    id: "mat-12",
    organizationId: "org-xmotion-1",
    brand: "Avery Dennison",
    name: "Supreme Wrap Gloss Nardo Grey",
    type: "cast_vinyl",
    thicknessMicrons: 80,
    finish: "Gloss",
    rollWidthMeters: 1.52,
    costPerMeter: 23,
    pricePerMeter: 62,
    currentStockMeters: 35.0,
    minimumStockAlertMeters: 15.0,
    unit: "meter",
    status: "available",
  },
];
