import {
  WorkOrderPhase,
  WorkOrderTimeEntry,
  MaterialUsage,
  QCInspection,
  QCItem,
} from "@/domains/production/types";

export const initialBMWPhases: WorkOrderPhase[] = [
  {
    id: "p-1",
    workOrderId: "wo-1",
    phaseKey: "prep_decontamination",
    name: "1. Lavagem & Descontaminação",
    status: "completed",
    orderIndex: 1,
    startedAt: "2026-08-28 09:30",
    completedAt: "2026-08-28 10:45",
    estimatedHours: 1.5,
    actualHours: 1.25,
    checklist: [
      {
        id: "c-1-1",
        phaseKey: "prep_decontamination",
        label: "Pré-lavagem com foam neutro e limpeza de cavas de roda",
        isCompleted: true,
        completedByName: "João Martins",
        completedAt: "2026-08-28 09:50",
      },
      {
        id: "c-1-2",
        phaseKey: "prep_decontamination",
        label: "Descontaminação férrica química e clay bar suave",
        isCompleted: true,
        completedByName: "João Martins",
        completedAt: "2026-08-28 10:20",
      },
      {
        id: "c-1-3",
        phaseKey: "prep_decontamination",
        label: "Secagem com ar comprimido e desengorduramento com álcool isopropílico (IPA)",
        isCompleted: true,
        completedByName: "João Martins",
        completedAt: "2026-08-28 10:45",
      },
    ],
  },
  {
    id: "p-2",
    workOrderId: "wo-1",
    phaseKey: "disassembly",
    name: "2. Desmontagem Técnica",
    status: "completed",
    orderIndex: 2,
    startedAt: "2026-08-28 10:45",
    completedAt: "2026-08-28 11:45",
    estimatedHours: 1.0,
    actualHours: 1.0,
    checklist: [
      {
        id: "c-2-1",
        phaseKey: "disassembly",
        label: "Desmontagem cuidada dos puxadores de porta e capas de espelhos",
        isCompleted: true,
        completedByName: "João Martins",
        completedAt: "2026-08-28 11:15",
      },
      {
        id: "c-2-2",
        phaseKey: "disassembly",
        label: "Remoção de emblemas M4 com fio de corte e limpeza de resíduos",
        isCompleted: true,
        completedByName: "João Martins",
        completedAt: "2026-08-28 11:45",
      },
    ],
  },
  {
    id: "p-3",
    workOrderId: "wo-1",
    phaseKey: "film_cutting",
    name: "3. Corte de Película & Traçados",
    status: "completed",
    orderIndex: 3,
    startedAt: "2026-08-28 11:45",
    completedAt: "2026-08-28 12:45",
    estimatedHours: 1.5,
    actualHours: 1.0,
    checklist: [
      {
        id: "c-3-1",
        phaseKey: "film_cutting",
        label: "Carregamento dos padrões digitais de corte (Plotter Software)",
        isCompleted: true,
        completedByName: "João Martins",
        completedAt: "2026-08-28 12:00",
      },
      {
        id: "c-3-2",
        phaseKey: "film_cutting",
        label: "Corte do rolo Stek DYNOshield com folgas de remate de 8mm",
        isCompleted: true,
        completedByName: "João Martins",
        completedAt: "2026-08-28 12:45",
      },
    ],
  },
  {
    id: "p-4",
    workOrderId: "wo-1",
    phaseKey: "application",
    name: "4. Aplicação de PPF por Painel",
    status: "in_progress",
    orderIndex: 4,
    startedAt: "2026-08-28 13:30",
    estimatedHours: 3.5,
    actualHours: 2.25,
    checklist: [
      {
        id: "c-4-1",
        phaseKey: "application",
        label: "Aplicação do Capô com solução de gel slip e tack",
        isCompleted: true,
        completedByName: "João Martins",
        completedAt: "2026-08-28 14:15",
      },
      {
        id: "c-4-2",
        phaseKey: "application",
        label: "Aplicação do Para-choques frontal e grelhas",
        isCompleted: true,
        completedByName: "João Martins",
        completedAt: "2026-08-28 15:30",
      },
      {
        id: "c-4-3",
        phaseKey: "application",
        label: "Aplicação das Portas e Guarda-lamas laterais",
        isCompleted: false,
      },
    ],
  },
  {
    id: "p-5",
    workOrderId: "wo-1",
    phaseKey: "assembly",
    name: "5. Remontagem & Ajuste de Folgas",
    status: "pending",
    orderIndex: 5,
    estimatedHours: 0.5,
    actualHours: 0,
    checklist: [
      {
        id: "c-5-1",
        phaseKey: "assembly",
        label: "Remontagem de puxadores e espelhos com verificação de aperto",
        isCompleted: false,
      },
    ],
  },
  {
    id: "p-6",
    workOrderId: "wo-1",
    phaseKey: "thermal_cure",
    name: "6. Cura Térmica & Pós-aquecimento",
    status: "pending",
    orderIndex: 6,
    estimatedHours: 0.5,
    actualHours: 0,
    checklist: [
      {
        id: "c-6-1",
        phaseKey: "thermal_cure",
        label: "Pós-aquecimento dos bordos e remates a 90°C com pirómetro digital",
        isCompleted: false,
      },
    ],
  },
  {
    id: "p-7",
    workOrderId: "wo-1",
    phaseKey: "detailing_finish",
    name: "7. Detailing Final & Selagem",
    status: "pending",
    orderIndex: 7,
    estimatedHours: 0.5,
    actualHours: 0,
    checklist: [
      {
        id: "c-7-1",
        phaseKey: "detailing_finish",
        label: "Limpeza de vidros, aspiração interior e selante cerâmico sobre PPF",
        isCompleted: false,
      },
    ],
  },
  {
    id: "p-8",
    workOrderId: "wo-1",
    phaseKey: "quality_control",
    name: "8. Controlo de Qualidade (QC)",
    status: "pending",
    orderIndex: 8,
    estimatedHours: 0.5,
    actualHours: 0,
    checklist: [
      {
        id: "c-8-1",
        phaseKey: "quality_control",
        label: "Inspeção final com lâmpada Scangrip e emissão do Certificado QC",
        isCompleted: false,
      },
    ],
  },
];

export const initialBMWTimeEntries: WorkOrderTimeEntry[] = [
  {
    id: "te-1",
    workOrderId: "wo-1",
    phaseKey: "prep_decontamination",
    technicianName: "João Martins",
    hoursSpent: 1.25,
    notes: "Descontaminação completa da pintura concluída.",
    createdAt: "2026-08-28 10:45",
  },
  {
    id: "te-2",
    workOrderId: "wo-1",
    phaseKey: "disassembly",
    technicianName: "João Martins",
    hoursSpent: 1.0,
    notes: "Puxadores e retrovisores removidos.",
    createdAt: "2026-08-28 11:45",
  },
  {
    id: "te-3",
    workOrderId: "wo-1",
    phaseKey: "film_cutting",
    technicianName: "João Martins",
    hoursSpent: 1.0,
    notes: "Corte de rolo Stek concluído com 8mm de remate.",
    createdAt: "2026-08-28 12:45",
  },
  {
    id: "te-4",
    workOrderId: "wo-1",
    phaseKey: "application",
    technicianName: "João Martins",
    hoursSpent: 2.25,
    notes: "Capô e para-choques aplicados. A finalizar laterais.",
    createdAt: "2026-08-28 15:45",
  },
];

export const initialBMWMaterialUsage: MaterialUsage = {
  id: "mu-1",
  workOrderId: "wo-1",
  materialId: "mat-1",
  materialName: "Stek DYNOshield Gloss PPF",
  batchNumber: "STEK-DS-2026-04",
  estimatedMeters: 16.5,
  actualMeters: 18.0,
  scrapPercentage: 9.1,
  rollWidthMeters: 1.52,
  costPerMeter: 48,
};

export const initialBMWQCItems: QCItem[] = [
  {
    id: "qc-1",
    criterionName: "Inspeção ótica sob luz Scangrip (sem pelos, pó ou contaminação)",
    category: "finish",
    status: "pass",
  },
  {
    id: "qc-2",
    criterionName: "Ausência total de bolhas de ar ou água residuais sob o filme",
    category: "finish",
    status: "pass",
  },
  {
    id: "qc-3",
    criterionName: "Remates e cantos embutidos 100% selados (sem película levantada)",
    category: "edges",
    status: "pass",
  },
  {
    id: "qc-4",
    criterionName: "Pós-aquecimento térmico validado a 90°C em todos os bordos",
    category: "edges",
    status: "pass",
  },
  {
    id: "qc-5",
    criterionName: "Alinhamento e folgas perfeitas de painéis após remontagem",
    category: "alignment",
    status: "pass",
  },
  {
    id: "qc-6",
    criterionName: "Sem marcas de corte ou lâmina na pintura, faróis ou borrachas",
    category: "finish",
    status: "pass",
  },
  {
    id: "qc-7",
    criterionName: "Vidros impecáveis, desengordurados e habitáculo aspirado",
    category: "cleanliness",
    status: "pass",
  },
  {
    id: "qc-8",
    criterionName: "Aperto e binário verificado nos pernos de segurança de jantes",
    category: "safety",
    status: "pass",
  },
  {
    id: "qc-9",
    criterionName: "Teste operacional de fecho de portas, câmaras 360° e sensores PDC",
    category: "safety",
    status: "pass",
  },
  {
    id: "qc-10",
    criterionName: "Registo fotográfico de conformidade 360° arquivado no passaporte",
    category: "finish",
    status: "pass",
  },
];

export const initialBMWQCInspection: QCInspection = {
  id: "qci-1",
  workOrderId: "wo-1",
  vehiclePlate: "44-TX-88",
  vehicleModel: "BMW M4 Competition Coupe",
  customerName: "AutoStand Prime Barcelos",
  inspectorName: "João Martins (Lead Detailer)",
  status: "passed",
  items: initialBMWQCItems,
  overallNotes: "Aplicação irrepreensível de Stek DYNOshield. Todos os cantos embutidos e cura térmica validada.",
  certificateNumber: "QC-2026-44TX88-PASS",
  approvedAt: "2026-08-28 16:30",
  createdAt: "2026-08-28 16:15",
};
