import { Quote } from "@/domains/quotes/types";
import { buildQuoteOptionFromParts } from "@/domains/quotes/pricing-engine";

export const initialQuotesData: Quote[] = [
  // 1. BMW M4 (AutoStand Prime - B2B with 12% discount)
  {
    id: "quote-1",
    organizationId: "org-xmotion-1",
    quoteNumber: "ORC-2026-042",
    vehicleId: "veh-1",
    vehiclePlate: "44-TX-88",
    vehicleModel: "BMW M4 Competition Coupe",
    vehicleYear: 2024,
    vehicleColor: "Black Sapphire Metallic",
    customerId: "c-b2b-1",
    customerName: "AutoStand Prime Barcelos",
    customerEmail: "comercial@autostandprime.pt",
    customerPhone: "912 345 678",
    customerType: "business",
    status: "approved",
    selectedOptionId: "opt-1-recommended",
    publicToken: "tok-bmw-m4-2026",
    expiresAt: "2026-09-10",
    notes: "Proposta B2B para Full PPF com desconto de 12% de frota contratual.",
    createdBy: "Luís Gonçalves",
    approvedAt: "2026-08-24T16:30:00Z",
    approvedByName: "Carlos Viana (AutoStand Prime)",
    createdAt: "2026-08-20T11:00:00Z",
    updatedAt: "2026-08-24T16:30:00Z",
    options: [
      buildQuoteOptionFromParts({
        quoteId: "quote-1",
        optionId: "opt-1-essential",
        tier: "essential",
        name: "Opção 1: Pack Frontal Standard",
        description: "Proteção frontal contra gravilha e impactos de autoestrada (Capô, Para-choques frontal e Óticas).",
        isRecommended: false,
        warrantyYears: 5,
        bodyType: "coupe",
        finish: "gloss",
        partCodes: ["hood", "front_bumper", "headlights"],
        materialName: "Stek DYNOshield Gloss",
        discountRate: 12,
      }),
      buildQuoteOptionFromParts({
        quoteId: "quote-1",
        optionId: "opt-1-recommended",
        tier: "recommended",
        name: "Opção 2: Pack Highway & Track",
        description: "Frente completa + Guarda-lamas, Espelhos, Embaladeiras e Soleiras de entrada.",
        isRecommended: true,
        warrantyYears: 10,
        bodyType: "coupe",
        finish: "gloss",
        partCodes: [
          "hood",
          "front_bumper",
          "front_fenders",
          "headlights",
          "mirrors",
          "rocker_panels",
          "door_sills",
        ],
        materialName: "Stek DYNOshield Gloss",
        discountRate: 12,
      }),
      buildQuoteOptionFromParts({
        quoteId: "quote-1",
        optionId: "opt-1-premium",
        tier: "premium",
        name: "Opção 3: Cobertura Integral Full Body PPF",
        description: "Proteção total de 100% da pintura em película acetinada Stek DYNOmatte com retornos estendidos em todas as arestas.",
        isRecommended: false,
        warrantyYears: 10,
        bodyType: "coupe",
        finish: "matte",
        partCodes: [
          "hood",
          "front_bumper",
          "front_fenders",
          "headlights",
          "mirrors",
          "doors",
          "rocker_panels",
          "rear_fenders",
          "pillars_a_b_c",
          "roof",
          "rear_bumper",
          "trunk_gate",
          "rear_spoiler",
          "door_sills",
        ],
        materialName: "Stek DYNOmatte Satin PPF",
        discountRate: 12,
      }),
    ],
    events: [
      {
        id: "qe-1",
        quoteId: "quote-1",
        eventType: "created",
        description: "Orçamento criado com 3 opções comparativas.",
        authorName: "Luís Gonçalves",
        createdAt: "2026-08-20 11:00",
      },
      {
        id: "qe-2",
        quoteId: "quote-1",
        eventType: "sent_whatsapp",
        description: "Proposta enviada por WhatsApp para Carlos Viana.",
        authorName: "Luís Gonçalves",
        createdAt: "2026-08-20 11:05",
      },
      {
        id: "qe-3",
        quoteId: "quote-1",
        eventType: "viewed_by_client",
        description: "Visualizado pelo cliente através de telemóvel.",
        createdAt: "2026-08-20 11:32",
      },
      {
        id: "qe-4",
        quoteId: "quote-1",
        eventType: "approved",
        description: "Opção 2 (Pack Highway & Track) aprovada digitalmente por Carlos Viana.",
        authorName: "Carlos Viana",
        createdAt: "2026-08-24 16:30",
      },
    ],
  },

  // 2. Porsche 911 Carrera (Bernardo Silva - Sent / Aguarda Resposta)
  {
    id: "quote-2",
    organizationId: "org-xmotion-1",
    quoteNumber: "ORC-2026-040",
    vehicleId: "veh-2",
    vehiclePlate: "99-PZ-11",
    vehicleModel: "Porsche 911 Carrera 4S (992)",
    vehicleYear: 2023,
    vehicleColor: "GT Silver Metallic",
    customerId: "c-part-1",
    customerName: "Bernardo Silva",
    customerEmail: "bernardo.silva@email.pt",
    customerPhone: "934 567 890",
    customerType: "individual",
    status: "sent",
    publicToken: "tok-porsche-911-2026",
    expiresAt: "2026-09-15",
    notes: "Cliente deseja transformar o acabamento da pintura para acetinado com película de alta espessura.",
    createdBy: "Luís Gonçalves",
    createdAt: "2026-08-24T14:00:00Z",
    updatedAt: "2026-08-24T14:15:00Z",
    options: [
      buildQuoteOptionFromParts({
        quoteId: "quote-2",
        optionId: "opt-2-essential",
        tier: "essential",
        name: "Opção 1: Pack Frontal Extended",
        description: "Capô, Para-choques frontal, Guarda-lamas e Óticas em película acetinada.",
        isRecommended: false,
        warrantyYears: 5,
        bodyType: "coupe",
        finish: "matte",
        partCodes: ["hood", "front_bumper", "front_fenders", "headlights", "mirrors"],
        materialName: "Stek DYNOmatte Satin PPF",
      }),
      buildQuoteOptionFromParts({
        quoteId: "quote-2",
        optionId: "opt-2-recommended",
        tier: "recommended",
        name: "Opção 2: Full Body Wrap Satin Grey",
        description: "Wrap completo da carroçaria com desmontagem detalhada de faróis, puxadores e emblemas.",
        isRecommended: true,
        warrantyYears: 7,
        bodyType: "coupe",
        finish: "satin",
        partCodes: [
          "hood",
          "front_bumper",
          "front_fenders",
          "doors",
          "rocker_panels",
          "rear_fenders",
          "roof",
          "rear_bumper",
          "trunk_gate",
          "rear_spoiler",
        ],
        materialName: "Avery Dennison SWF Satin Black/Grey",
      }),
      buildQuoteOptionFromParts({
        quoteId: "quote-2",
        optionId: "opt-2-premium",
        tier: "premium",
        name: "Opção 3: Full Body PPF Matte + Tratamento Cerâmico de Jantes",
        description: "Proteção total com PPF auto-regenerativo mate de 200 microns e cerâmica de alta dureza.",
        isRecommended: false,
        warrantyYears: 10,
        bodyType: "coupe",
        finish: "matte",
        partCodes: [
          "hood",
          "front_bumper",
          "front_fenders",
          "headlights",
          "mirrors",
          "doors",
          "rocker_panels",
          "rear_fenders",
          "pillars_a_b_c",
          "roof",
          "rear_bumper",
          "trunk_gate",
          "rear_spoiler",
          "door_sills",
        ],
        materialName: "Stek DYNOmatte Satin PPF",
      }),
    ],
    events: [
      {
        id: "qe-201",
        quoteId: "quote-2",
        eventType: "created",
        description: "Orçamento gerado pelo configurador.",
        authorName: "Luís Gonçalves",
        createdAt: "2026-08-24 14:00",
      },
      {
        id: "qe-202",
        quoteId: "quote-2",
        eventType: "sent_whatsapp",
        description: "Link seguro de aprovação partilhado via WhatsApp.",
        authorName: "Luís Gonçalves",
        createdAt: "2026-08-24 14:15",
      },
      {
        id: "qe-203",
        quoteId: "quote-2",
        eventType: "viewed_by_client",
        description: "Visualizado pelo cliente há 1 dia.",
        createdAt: "2026-08-27 18:20",
      },
    ],
  },

  // 3. BMW M2 CS (Gonçalo Ramos - >4 dias a aguardar resposta)
  {
    id: "quote-3",
    organizationId: "org-xmotion-1",
    quoteNumber: "ORC-2026-041",
    vehicleId: "veh-9",
    vehiclePlate: "02-CS-22",
    vehicleModel: "BMW M2 CS (F87)",
    vehicleYear: 2021,
    vehicleColor: "Misano Blue Metallic",
    customerId: "c-part-5",
    customerName: "Gonçalo Ramos",
    customerEmail: "goncalo.ramos@email.pt",
    customerPhone: "931 234 888",
    customerType: "individual",
    status: "sent",
    publicToken: "tok-bmw-m2-2026",
    expiresAt: "2026-09-05",
    notes: "Aguardar resposta do cliente há 5 dias (valor total de proposta: € 3.850).",
    createdBy: "Luís Gonçalves",
    createdAt: "2026-08-20T14:20:00Z",
    updatedAt: "2026-08-20T14:30:00Z",
    options: [
      buildQuoteOptionFromParts({
        quoteId: "quote-3",
        optionId: "opt-3-essential",
        tier: "essential",
        name: "Opção 1: Pack Frontal Track",
        description: "Proteção frontal completa para utilização intensiva em circuito.",
        isRecommended: false,
        warrantyYears: 5,
        bodyType: "coupe",
        finish: "gloss",
        partCodes: ["hood", "front_bumper", "front_fenders", "headlights", "mirrors"],
        materialName: "SunTek Reaction Gloss PPF",
      }),
      buildQuoteOptionFromParts({
        quoteId: "quote-3",
        optionId: "opt-3-recommended",
        tier: "recommended",
        name: "Opção 2: Full Body Color PPF Satin Black",
        description: "Mudança de cor para Preto Acetinado mantendo capacidade auto-regenerativa do PPF.",
        isRecommended: true,
        warrantyYears: 10,
        bodyType: "coupe",
        finish: "color_ppf",
        partCodes: [
          "hood",
          "front_bumper",
          "front_fenders",
          "doors",
          "rocker_panels",
          "rear_fenders",
          "roof",
          "rear_bumper",
          "trunk_gate",
          "rear_spoiler",
        ],
        materialName: "Stek DYNOcarbon & Color PPF",
      }),
      buildQuoteOptionFromParts({
        quoteId: "quote-3",
        optionId: "opt-3-premium",
        tier: "premium",
        name: "Opção 3: Cobertura Integral + Pack Carbono Expósito",
        description: "PPF integral com destaque de acabamento em fibra de carbono brilhante no tejadilho e difusor.",
        isRecommended: false,
        warrantyYears: 10,
        bodyType: "coupe",
        finish: "color_ppf",
        partCodes: [
          "hood",
          "front_bumper",
          "front_fenders",
          "headlights",
          "mirrors",
          "doors",
          "rocker_panels",
          "rear_fenders",
          "pillars_a_b_c",
          "roof",
          "rear_bumper",
          "trunk_gate",
          "rear_spoiler",
          "door_sills",
        ],
        materialName: "Stek DYNOcarbon Gloss PPF",
      }),
    ],
    events: [
      {
        id: "qe-301",
        quoteId: "quote-3",
        eventType: "created",
        description: "Orçamento criado e emitido.",
        authorName: "Luís Gonçalves",
        createdAt: "2026-08-20 14:20",
      },
      {
        id: "qe-302",
        quoteId: "quote-3",
        eventType: "sent_whatsapp",
        description: "Mensagem e link de aprovação enviados.",
        authorName: "Luís Gonçalves",
        createdAt: "2026-08-20 14:30",
      },
    ],
  },

  // 4. Porsche Macan GTS (Inês Carvalho - >4 dias)
  {
    id: "quote-4",
    organizationId: "org-xmotion-1",
    quoteNumber: "ORC-2026-038",
    vehicleId: "veh-11",
    vehiclePlate: "77-PO-88",
    vehicleModel: "Porsche Macan GTS",
    vehicleYear: 2023,
    vehicleColor: "Carmine Red",
    customerId: "c-part-10",
    customerName: "Inês Carvalho",
    customerEmail: "ines.carvalho@email.pt",
    customerPhone: "962 334 455",
    customerType: "individual",
    status: "sent",
    publicToken: "tok-porsche-macan-2026",
    expiresAt: "2026-09-08",
    notes: "Aguardar decisão entre Pack Frontal ou Cobertura Integral.",
    createdBy: "Luís Gonçalves",
    createdAt: "2026-08-24T10:00:00Z",
    updatedAt: "2026-08-24T10:10:00Z",
    options: [
      buildQuoteOptionFromParts({
        quoteId: "quote-4",
        optionId: "opt-4-essential",
        tier: "essential",
        name: "Opção 1: Pack Proteção de Óticas e Puxadores",
        description: "Proteção leve das áreas mais vulneráveis a desgaste diário.",
        isRecommended: false,
        warrantyYears: 5,
        bodyType: "suv",
        finish: "gloss",
        partCodes: ["headlights", "mirrors", "door_sills"],
        materialName: "Stek DYNOshield Gloss",
      }),
      buildQuoteOptionFromParts({
        quoteId: "quote-4",
        optionId: "opt-4-recommended",
        tier: "recommended",
        name: "Opção 2: Pack Frontal SUV Completo",
        description: "Capô, Para-choques frontal, Guarda-lamas e Óticas.",
        isRecommended: true,
        warrantyYears: 10,
        bodyType: "suv",
        finish: "gloss",
        partCodes: ["hood", "front_bumper", "front_fenders", "headlights", "mirrors"],
        materialName: "Stek DYNOshield Gloss",
      }),
      buildQuoteOptionFromParts({
        quoteId: "quote-4",
        optionId: "opt-4-premium",
        tier: "premium",
        name: "Opção 3: Cobertura Integral SUV Full PPF",
        description: "Proteção total de todas as superfícies pintadas.",
        isRecommended: false,
        warrantyYears: 10,
        bodyType: "suv",
        finish: "gloss",
        partCodes: [
          "hood",
          "front_bumper",
          "front_fenders",
          "headlights",
          "mirrors",
          "doors",
          "rocker_panels",
          "rear_fenders",
          "roof",
          "rear_bumper",
          "trunk_gate",
          "door_sills",
        ],
        materialName: "SunTek Reaction Gloss PPF",
      }),
    ],
    events: [
      {
        id: "qe-401",
        quoteId: "quote-4",
        eventType: "created",
        description: "Orçamento criado com 3 opções.",
        authorName: "Luís Gonçalves",
        createdAt: "2026-08-24 10:00",
      },
    ],
  },

  // 5. Audi RS6 Avant (Tiago Cerqueira - Approved)
  {
    id: "quote-5",
    organizationId: "org-xmotion-1",
    quoteNumber: "ORC-2026-039",
    vehicleId: "veh-3",
    vehiclePlate: "12-RS-66",
    vehicleModel: "Audi RS6 Avant V8 BiTurbo (C8)",
    vehicleYear: 2022,
    vehicleColor: "Nardo Grey",
    customerId: "c-part-3",
    customerName: "Tiago Cerqueira",
    customerEmail: "tiago.cerqueira@email.pt",
    customerPhone: "967 890 123",
    customerType: "individual",
    status: "approved",
    selectedOptionId: "opt-5-recommended",
    publicToken: "tok-audi-rs6-2026",
    expiresAt: "2026-09-01",
    notes: "Aprovado pelo cliente. Trabalho em curso na oficina.",
    createdBy: "Luís Gonçalves",
    approvedAt: "2026-08-26T18:00:00Z",
    approvedByName: "Tiago Cerqueira",
    createdAt: "2026-08-22T15:00:00Z",
    updatedAt: "2026-08-26T18:00:00Z",
    options: [
      buildQuoteOptionFromParts({
        quoteId: "quote-5",
        optionId: "opt-5-essential",
        tier: "essential",
        name: "Opção 1: Pack Frontal Standard",
        description: "Proteção de frente standard.",
        isRecommended: false,
        warrantyYears: 5,
        bodyType: "wagon",
        finish: "gloss",
        partCodes: ["hood", "front_bumper", "headlights"],
        materialName: "Stek DYNOshield Gloss",
      }),
      buildQuoteOptionFromParts({
        quoteId: "quote-5",
        optionId: "opt-5-recommended",
        tier: "recommended",
        name: "Opção 2: Pack Frontal Completo + Tratamento Cerâmico",
        description: "PPF na frente total e cerâmica Gyeon Q2 Mohs EVO no restante veículo.",
        isRecommended: true,
        warrantyYears: 10,
        bodyType: "wagon",
        finish: "gloss",
        partCodes: ["hood", "front_bumper", "front_fenders", "headlights", "mirrors", "door_sills"],
        materialName: "Stek DYNOshield Gloss",
      }),
      buildQuoteOptionFromParts({
        quoteId: "quote-5",
        optionId: "opt-5-premium",
        tier: "premium",
        name: "Opção 3: Cobertura Integral Full Body PPF",
        description: "PPF integral em toda a carrinha.",
        isRecommended: false,
        warrantyYears: 10,
        bodyType: "wagon",
        finish: "gloss",
        partCodes: [
          "hood",
          "front_bumper",
          "front_fenders",
          "headlights",
          "mirrors",
          "doors",
          "rocker_panels",
          "rear_fenders",
          "roof",
          "rear_bumper",
          "trunk_gate",
          "door_sills",
        ],
        materialName: "Stek DYNOshield Gloss",
      }),
    ],
    events: [
      {
        id: "qe-501",
        quoteId: "quote-5",
        eventType: "created",
        description: "Orçamento emitido.",
        authorName: "Luís Gonçalves",
        createdAt: "2026-08-22 15:00",
      },
      {
        id: "qe-502",
        quoteId: "quote-5",
        eventType: "approved",
        description: "Aprovado digitalmente por Tiago Cerqueira.",
        authorName: "Tiago Cerqueira",
        createdAt: "2026-08-26 18:00",
      },
    ],
  },

  // 6. Ferrari 488 GTB (Duarte Faria - Approved)
  {
    id: "quote-6",
    organizationId: "org-xmotion-1",
    quoteNumber: "ORC-2026-037",
    vehicleId: "veh-6",
    vehiclePlate: "48-FE-88",
    vehicleModel: "Ferrari 488 GTB",
    vehicleYear: 2019,
    vehicleColor: "Rosso Corsa",
    customerId: "c-part-6",
    customerName: "Duarte Faria",
    customerEmail: "duarte.faria@email.pt",
    customerPhone: "965 432 109",
    customerType: "individual",
    status: "approved",
    selectedOptionId: "opt-6-premium",
    publicToken: "tok-ferrari-488-2026",
    expiresAt: "2026-08-30",
    notes: "Cliente selecionou a opção de Proteção Integral.",
    createdBy: "Luís Gonçalves",
    approvedAt: "2026-08-15T16:00:00Z",
    approvedByName: "Duarte Faria",
    createdAt: "2026-08-12T10:00:00Z",
    updatedAt: "2026-08-15T16:00:00Z",
    options: [
      buildQuoteOptionFromParts({
        quoteId: "quote-6",
        optionId: "opt-6-premium",
        tier: "premium",
        name: "Opção 3: Cobertura Integral Ultra Gloss",
        description: "Full PPF de 200 microns com garantia de 10 anos.",
        isRecommended: true,
        warrantyYears: 10,
        bodyType: "coupe",
        finish: "gloss",
        partCodes: [
          "hood",
          "front_bumper",
          "front_fenders",
          "headlights",
          "mirrors",
          "doors",
          "rocker_panels",
          "rear_fenders",
          "roof",
          "rear_bumper",
          "trunk_gate",
          "rear_spoiler",
          "door_sills",
        ],
        materialName: "Stek DYNOshield Gloss",
      }),
    ],
    events: [
      {
        id: "qe-601",
        quoteId: "quote-6",
        eventType: "created",
        description: "Orçamento emitido.",
        authorName: "Luís Gonçalves",
        createdAt: "2026-08-12 10:00",
      },
    ],
  },

  // 7. Apex Track & Club Porsche GT3 RS (Draft)
  {
    id: "quote-7",
    organizationId: "org-xmotion-1",
    quoteNumber: "ORC-2026-043",
    vehicleId: "veh-15",
    vehiclePlate: "99-GT-03",
    vehicleModel: "Porsche 911 GT3 RS (992)",
    vehicleYear: 2024,
    vehicleColor: "Guards Red",
    customerId: "c-b2b-2",
    customerName: "Apex Track & Club",
    customerEmail: "gestao@apexclub.pt",
    customerPhone: "918 765 432",
    customerType: "business",
    status: "draft",
    publicToken: "tok-porsche-gt3-2026",
    expiresAt: "2026-09-20",
    notes: "Rascunho de proposta para pacote de pista (PPF ultra resistente a impactos).",
    createdBy: "Luís Gonçalves",
    createdAt: "2026-08-28T09:00:00Z",
    updatedAt: "2026-08-28T09:00:00Z",
    options: [
      buildQuoteOptionFromParts({
        quoteId: "quote-7",
        optionId: "opt-7-track",
        tier: "recommended",
        name: "Opção: Track High-Impact Pack (250µm)",
        description: "Película SunTek Ultra Defence de 250 microns nos arcos de roda, difusor e capô em carbono exposto.",
        isRecommended: true,
        warrantyYears: 10,
        bodyType: "coupe",
        finish: "gloss",
        partCodes: ["hood", "front_bumper", "front_fenders", "rocker_panels", "rear_fenders", "door_sills"],
        materialName: "SunTek Ultra Defence 250u",
        discountRate: 10,
      }),
    ],
    events: [
      {
        id: "qe-701",
        quoteId: "quote-7",
        eventType: "created",
        description: "Rascunho criado.",
        authorName: "Luís Gonçalves",
        createdAt: "2026-08-28 09:00",
      },
    ],
  },
];
