import { VehicleTimeBookModel, B2BAccount } from "@/domains/timebook/types";

export const initialTimeBookModels: VehicleTimeBookModel[] = [
  {
    id: "tb-audi-rs6",
    make: "Audi",
    model: "RS6 Avant V8 BiTurbo",
    generationYear: 2023,
    bodyType: "station_wagon",
    serviceType: "Wrap",
    totalEstimatedHours: 36.0,
    totalMedianHours: 34.5,
    totalSamples: 4,
    overallConfidence: "initial",
    notes: "Caso-base X-Motion: Extrapolação inicial de 32–40 h totais a partir de amostra parcial de 8 h. Requer mais viaturas para maturidade.",
    panels: [
      {
        panelCode: "front_bumper",
        panelName: "Para-choques Dianteiro & Grelha RS",
        serviceType: "Wrap",
        medianMinutes: 240, // 4h
        minMinutes: 210,
        maxMinutes: 270,
        sampleCount: 4,
        confidence: "initial",
      },
      {
        panelCode: "hood",
        panelName: "Capô do Motor",
        serviceType: "Wrap",
        medianMinutes: 120, // 2h
        minMinutes: 105,
        maxMinutes: 135,
        sampleCount: 4,
        confidence: "initial",
      },
      {
        panelCode: "fenders_front",
        panelName: "Guarda-lamas Dianteiros (Esq + Dir)",
        serviceType: "Wrap",
        medianMinutes: 120, // 2h
        minMinutes: 110,
        maxMinutes: 140,
        sampleCount: 4,
        confidence: "initial",
      },
      {
        panelCode: "doors",
        panelName: "Portas Laterais (4 Unidades)",
        serviceType: "Wrap",
        medianMinutes: 480, // 8h
        minMinutes: 440,
        maxMinutes: 520,
        sampleCount: 3,
        confidence: "initial",
      },
      {
        panelCode: "rear_quarter",
        panelName: "Painéis Laterais Traseiros & Pilares C",
        serviceType: "Wrap",
        medianMinutes: 360, // 6h
        minMinutes: 330,
        maxMinutes: 390,
        sampleCount: 3,
        confidence: "initial",
      },
    ],
  },
  {
    id: "tb-bmw-m4",
    make: "BMW",
    model: "M4 Competition Coupe (G82)",
    generationYear: 2024,
    bodyType: "coupe",
    serviceType: "PPF",
    totalEstimatedHours: 35.0,
    totalMedianHours: 33.0,
    totalSamples: 18,
    overallConfidence: "reliable",
    notes: "Benchmark maduro e fiável (>15 viaturas completas). Tempo médio por painel estabilizado.",
    panels: [
      {
        panelCode: "front_bumper",
        panelName: "Para-choques Dianteiro & Entradas M",
        serviceType: "PPF",
        medianMinutes: 270,
        minMinutes: 240,
        maxMinutes: 300,
        sampleCount: 18,
        confidence: "reliable",
      },
      {
        panelCode: "hood",
        panelName: "Capô com Cavidades M",
        serviceType: "PPF",
        medianMinutes: 150,
        minMinutes: 130,
        maxMinutes: 170,
        sampleCount: 18,
        confidence: "reliable",
      },
      {
        panelCode: "roof_carbon",
        panelName: "Tejadilho em Carbono",
        serviceType: "PPF",
        medianMinutes: 120,
        minMinutes: 100,
        maxMinutes: 135,
        sampleCount: 18,
        confidence: "reliable",
      },
      {
        panelCode: "fenders",
        panelName: "Guarda-lamas c/ Brânquias M",
        serviceType: "PPF",
        medianMinutes: 180,
        minMinutes: 160,
        maxMinutes: 210,
        sampleCount: 18,
        confidence: "reliable",
      },
    ],
  },
  {
    id: "tb-porsche-911",
    make: "Porsche",
    model: "911 Carrera 4S (992)",
    generationYear: 2023,
    bodyType: "coupe",
    serviceType: "Wrap",
    totalEstimatedHours: 32.0,
    totalMedianHours: 30.5,
    totalSamples: 12,
    overallConfidence: "learning",
    notes: "12 amostras registadas. Curvatura das ancas traseiras exige pré-estiramento controlado.",
    panels: [
      {
        panelCode: "rear_hips",
        panelName: "Ancas Traseiras & Guarda-lamas Largos",
        serviceType: "Wrap",
        medianMinutes: 300,
        minMinutes: 270,
        maxMinutes: 330,
        sampleCount: 12,
        confidence: "learning",
      },
      {
        panelCode: "front_bumper",
        panelName: "Para-choques Dianteiro Aerodinâmico",
        serviceType: "Wrap",
        medianMinutes: 240,
        minMinutes: 210,
        maxMinutes: 260,
        sampleCount: 12,
        confidence: "learning",
      },
    ],
  },
];

export const initialB2BAccounts: B2BAccount[] = [
  {
    id: "b2b-1",
    companyName: "AutoStand Prime Barcelos, Lda.",
    tradeName: "AutoStand Prime",
    nif: "PT509887766",
    contactPerson: "Miguel Ângelo Costa (Diretor Comercial)",
    contactEmail: "comercial@autostandprime.pt",
    contactPhone: "+351 912 345 678",
    discountRate: 15,
    paymentTermsDays: 30,
    currentBalanceCents: 492000,
    totalBilledCents: 3840000,
    fleetVehicles: [
      {
        id: "fv-1",
        plate: "44-TX-88",
        make: "BMW",
        model: "M4 Competition Coupe",
        service: "Full PPF Stek DYNOshield",
        status: "delivered",
        deliveryDueDate: "2026-08-28",
        assignedTechnician: "João Martins",
        amountCents: 492000,
      },
      {
        id: "fv-2",
        plate: "88-ZZ-99",
        make: "Porsche",
        model: "Taycan 4S Cross Turismo",
        service: "PPF Frontal Completo & Cerâmica",
        status: "in_production",
        deliveryDueDate: "2026-09-02",
        assignedTechnician: "Rodrigo Santos",
        amountCents: 245000,
      },
    ],
  },
  {
    id: "b2b-2",
    companyName: "Minho Motors Concessionário Oficial, S.A.",
    tradeName: "Minho Motors",
    nif: "PT508112233",
    contactPerson: "Carlos Guimarães (Gestor de Frotas)",
    contactEmail: "frotas@minhomotors.pt",
    contactPhone: "+351 933 445 566",
    discountRate: 12,
    paymentTermsDays: 30,
    currentBalanceCents: 270600,
    totalBilledCents: 2450000,
    fleetVehicles: [
      {
        id: "fv-3",
        plate: "12-RS-66",
        make: "Audi",
        model: "RS6 Avant V8 BiTurbo",
        service: "Wrap Completo Satin Dark Grey",
        status: "delivered",
        deliveryDueDate: "2026-08-27",
        assignedTechnician: "João Martins",
        amountCents: 270600,
      },
    ],
  },
];
