import { Vehicle } from "@/domains/vehicles/types";

export const initialVehiclesData: Vehicle[] = [
  // 1. BMW M4
  {
    id: "veh-1",
    organizationId: "org-xmotion-1",
    plateDisplay: "44-TX-88",
    plateNormalized: "44TX88",
    vin: "WBA33AY05PFP12345",
    make: "BMW",
    model: "M4 Competition Coupe",
    generationYear: 2024,
    bodyType: "coupe",
    originalColorName: "Black Sapphire Metallic",
    originalColorFamily: "black",
    originalColorCode: "475",
    currentMileage: 4200,
    fuelType: "gasoline",
    notes: "Viatura em preparação para Full PPF com acabamento acetinado.",
    photoUrl: "/vehicles/bmw-m4.png",
    createdAt: "2026-08-20T10:00:00Z",
    updatedAt: "2026-08-28T10:00:00Z",
    currentOwner: {
      customerId: "c-b2b-1",
      customerName: "AutoStand Prime Barcelos",
      customerType: "business",
      since: "2026-08-20",
    },
    ownerHistory: [
      {
        id: "link-1",
        vehicleId: "veh-1",
        customerId: "c-b2b-1",
        customerName: "AutoStand Prime Barcelos",
        relationshipType: "owner",
        startedAt: "2026-08-20",
        isCurrent: true,
      },
    ],
    timeline: [
      {
        id: "tl-1",
        vehicleId: "veh-1",
        type: "checkin",
        title: "Check-in Fotográfico Concluído",
        description: "12 fotografias capturadas incluindo tejadilho e odómetro (4.200 km). Danos prévios registados no para-choques.",
        date: "2026-08-28 09:15",
        authorName: "João Martins",
        badgeText: "Check-in OK",
      },
      {
        id: "tl-2",
        vehicleId: "veh-1",
        type: "work_order",
        title: "Início da Aplicação de PPF Completo",
        description: "Trabalho atribuído ao técnico João Martins. Sequência: tejadilho -> portas -> frente.",
        date: "2026-08-28 10:00",
        authorName: "Luís Gonçalves",
        badgeText: "Em Curso (65%)",
      },
      {
        id: "tl-3",
        vehicleId: "veh-1",
        type: "quote",
        title: "Orçamento #ORC-2026-042 Aprovado",
        description: "Opção Cobertura Integral aprovada por Carlos Viana (€ 3.500 c/ IVA).",
        date: "2026-08-24 16:30",
        authorName: "Carlos Viana",
        badgeText: "Aprovado",
      },
    ],
    technicalNotes: [
      {
        id: "tn-1",
        vehicleId: "veh-1",
        authorName: "João Martins",
        category: "technical",
        content: "Grelha frontal com sensores ADAS delicados. Requer remoção cuidadosa dos emblemas.",
        createdAt: "2026-08-28T09:30:00Z",
      },
    ],
  },
  // 2. Porsche 911 Carrera
  {
    id: "veh-2",
    organizationId: "org-xmotion-1",
    plateDisplay: "99-PZ-11",
    plateNormalized: "99PZ11",
    vin: "WP0AB2A93PS123987",
    make: "Porsche",
    model: "911 Carrera 4S (992)",
    generationYear: 2023,
    bodyType: "coupe",
    originalColorName: "GT Silver Metallic",
    originalColorFamily: "silver",
    originalColorCode: "M7Z",
    currentMileage: 18500,
    fuelType: "gasoline",
    notes: "Wrap Integral em Vinil Satin Dark Grey com retornos estendidos.",
    createdAt: "2026-04-12T15:30:00Z",
    updatedAt: "2026-08-28T12:00:00Z",
    currentOwner: {
      customerId: "c-part-1",
      customerName: "Bernardo Silva",
      customerType: "individual",
      since: "2026-04-12",
    },
    ownerHistory: [
      {
        id: "link-2",
        vehicleId: "veh-2",
        customerId: "c-part-1",
        customerName: "Bernardo Silva",
        relationshipType: "owner",
        startedAt: "2026-04-12",
        isCurrent: true,
      },
    ],
    timeline: [
      {
        id: "tl-201",
        vehicleId: "veh-2",
        type: "work_order",
        title: "Aplicação de Wrap — Laterais e Portas",
        description: "Técnico Rui Almeida em execução. Retornos em processo de conformação térmica.",
        date: "2026-08-28 12:00",
        authorName: "Rui Almeida",
        badgeText: "Em Curso (40%)",
      },
      {
        id: "tl-202",
        vehicleId: "veh-2",
        type: "checkin",
        title: "Check-in de Entrada",
        description: "Check-in realizado com odómetro a 18.500 km. Estado da pintura original sem picadas graves.",
        date: "2026-08-28 08:45",
        authorName: "Rui Almeida",
      },
    ],
  },
  // 3. Audi RS6 Avant
  {
    id: "veh-3",
    organizationId: "org-xmotion-1",
    plateDisplay: "12-RS-66",
    plateNormalized: "12RS66",
    vin: "WAUZZZF28NA098765",
    make: "Audi",
    model: "RS6 Avant V8 BiTurbo (C8)",
    generationYear: 2022,
    bodyType: "wagon",
    originalColorName: "Nardo Grey",
    originalColorFamily: "grey",
    originalColorCode: "LY7C",
    currentMileage: 34200,
    fuelType: "gasoline",
    notes: "Exemplo demonstrativo de histórico técnico preservado após mudança de proprietário.",
    createdAt: "2025-11-10T14:00:00Z",
    updatedAt: "2026-08-28T09:00:00Z",
    currentOwner: {
      customerId: "c-part-3",
      customerName: "Tiago Cerqueira",
      customerType: "individual",
      since: "2026-06-02",
    },
    ownerHistory: [
      {
        id: "link-3a",
        vehicleId: "veh-3",
        customerId: "c-part-11",
        customerName: "Fernando Couto",
        relationshipType: "owner",
        startedAt: "2025-11-10",
        endedAt: "2026-06-01",
        isCurrent: false,
      },
      {
        id: "link-3b",
        vehicleId: "veh-3",
        customerId: "c-part-3",
        customerName: "Tiago Cerqueira",
        relationshipType: "owner",
        startedAt: "2026-06-02",
        isCurrent: true,
      },
    ],
    timeline: [
      {
        id: "tl-301",
        vehicleId: "veh-3",
        type: "work_order",
        title: "PPF Frontal — Conclusão de Para-choques e Capô",
        description: "Tempo registado: 6h de aplicação líquida. Alimenta a base do Time Book.",
        date: "2026-08-28 09:00",
        authorName: "Pedro Santos",
        badgeText: "Em Curso (75%)",
      },
      {
        id: "tl-302",
        vehicleId: "veh-3",
        type: "owner_changed",
        title: "Transferência de Posse da Viatura",
        description: "Proprietário atualizado de Fernando Couto para Tiago Cerqueira. Passaporte técnico integralmente preservado.",
        date: "2026-06-02 10:00",
        authorName: "Luís Gonçalves",
      },
      {
        id: "tl-303",
        vehicleId: "veh-3",
        type: "service_completed",
        title: "Tratamento Cerâmico de Jantes e Vidros",
        description: "Serviço realizado e certificado no sistema sob a posse anterior.",
        date: "2025-12-15 17:00",
        authorName: "Pedro Santos",
      },
    ],
  },
  // 4. Mercedes GLC
  {
    id: "veh-4",
    organizationId: "org-xmotion-1",
    plateDisplay: "78-MB-22",
    plateNormalized: "78MB22",
    vin: "WDC2539841F567890",
    make: "Mercedes-Benz",
    model: "GLC Coupe 300d",
    generationYear: 2023,
    bodyType: "suv",
    originalColorName: "Obsidian Black Metallic",
    originalColorFamily: "black",
    originalColorCode: "197",
    currentMileage: 28400,
    fuelType: "diesel",
    notes: "Chrome Delete integral nos frisos de janelas, barras de tejadilho e difusor traseiro.",
    createdAt: "2026-05-18T11:00:00Z",
    updatedAt: "2026-08-28T14:00:00Z",
    currentOwner: {
      customerId: "c-part-2",
      customerName: "Miguel Ângelo Costa",
      customerType: "individual",
      since: "2026-05-18",
    },
    timeline: [
      {
        id: "tl-401",
        vehicleId: "veh-4",
        type: "work_order",
        title: "Chrome Delete em Pausa — A Guardar Fitas Especiais",
        description: "Material específico para difusor traseiro reservado do stock com chegada prevista hoje às 16h.",
        date: "2026-08-28 14:00",
        authorName: "Miguel Costa",
        badgeText: "A Guardar Peças (20%)",
      },
    ],
  },
  // 5. Tesla Model 3
  {
    id: "veh-5",
    organizationId: "org-xmotion-1",
    plateDisplay: "33-TS-99",
    plateNormalized: "33TS99",
    vin: "5YJ3E1EB8PF112233",
    make: "Tesla",
    model: "Model 3 Long Range",
    generationYear: 2024,
    bodyType: "sedan",
    originalColorName: "Pearl White Multi-Coat",
    originalColorFamily: "white",
    originalColorCode: "PPSW",
    currentMileage: 8900,
    fuelType: "electric",
    notes: "Agendamento de detailing interior e aplicação de película de proteção no ecrã central.",
    createdAt: "2026-06-20T10:15:00Z",
    updatedAt: "2026-08-28T16:00:00Z",
    currentOwner: {
      customerId: "c-part-4",
      customerName: "Ana Rita Ferreira",
      customerType: "individual",
      since: "2026-06-20",
    },
  },
  // 6. Ferrari 488 GTB
  {
    id: "veh-6",
    organizationId: "org-xmotion-1",
    plateDisplay: "48-FE-88",
    plateNormalized: "48FE88",
    vin: "ZFF79LLA8H0223344",
    make: "Ferrari",
    model: "488 GTB",
    generationYear: 2019,
    bodyType: "coupe",
    originalColorName: "Rosso Corsa",
    originalColorFamily: "red",
    originalColorCode: "322",
    currentMileage: 14500,
    fuelType: "gasoline",
    notes: "Full PPF Ultra Gloss de alta espessura (200 microns).",
    createdAt: "2026-03-10T12:00:00Z",
    updatedAt: "2026-08-15T15:30:00Z",
    currentOwner: {
      customerId: "c-part-6",
      customerName: "Duarte Faria",
      customerType: "individual",
      since: "2026-03-10",
    },
    timeline: [
      {
        id: "tl-601",
        vehicleId: "veh-6",
        type: "warranty_issued",
        title: "Certificado de Garantia PPF de 10 Anos Emitido",
        description: "Material: Stek DYNOshield (Lote STK-2026-03). Próxima revisão agendada para 2027-03.",
        date: "2026-03-25 18:00",
        authorName: "Luís Gonçalves",
        badgeText: "Garantia 10 Anos",
      },
    ],
  },
  // 7. Ducati Panigale V4
  {
    id: "veh-7",
    organizationId: "org-xmotion-1",
    plateDisplay: "14-DU-04",
    plateNormalized: "14DU04",
    vin: "ZDM14B007LB001122",
    make: "Ducati",
    model: "Panigale V4 S",
    generationYear: 2023,
    bodyType: "motorcycle",
    originalColorName: "Ducati Red",
    originalColorFamily: "red",
    originalColorCode: "DR-01",
    currentMileage: 3800,
    fuelType: "gasoline",
    notes: "PPF de depósito e carenagens frontais.",
    createdAt: "2026-05-02T16:00:00Z",
    updatedAt: "2026-08-04T17:20:00Z",
    currentOwner: {
      customerId: "c-part-8",
      customerName: "Pedro Álvares",
      customerType: "individual",
      since: "2026-05-02",
    },
  },
  // 8. Land Rover Defender 110
  {
    id: "veh-8",
    organizationId: "org-xmotion-1",
    plateDisplay: "90-LR-11",
    plateNormalized: "90LR11",
    vin: "SALWR2V44PA998877",
    make: "Land Rover",
    model: "Defender 110 D300 HSE",
    generationYear: 2024,
    bodyType: "suv",
    originalColorName: "Fuji White",
    originalColorFamily: "white",
    originalColorCode: "867",
    currentMileage: 11200,
    fuelType: "diesel",
    notes: "Color PPF Verde Militar Mate (Satin Khaki Green).",
    createdAt: "2026-04-25T11:10:00Z",
    updatedAt: "2026-07-28T16:40:00Z",
    currentOwner: {
      customerId: "c-part-9",
      customerName: "Vasco Moreira",
      customerType: "individual",
      since: "2026-04-25",
    },
  },
  // 9. BMW M2 CS
  {
    id: "veh-9",
    organizationId: "org-xmotion-1",
    plateDisplay: "02-CS-22",
    plateNormalized: "02CS22",
    vin: "WBS1J91020FP88776",
    make: "BMW",
    model: "M2 CS (F87)",
    generationYear: 2021,
    bodyType: "coupe",
    originalColorName: "Misano Blue Metallic",
    originalColorFamily: "blue",
    originalColorCode: "C1D",
    currentMileage: 19800,
    fuelType: "gasoline",
    notes: "Proposta de Full Color PPF Satin Black.",
    createdAt: "2026-08-20T14:20:00Z",
    updatedAt: "2026-08-26T18:00:00Z",
    currentOwner: {
      customerId: "c-part-5",
      customerName: "Gonçalo Ramos",
      customerType: "individual",
      since: "2026-08-20",
    },
  },
  // 10. Mercedes A45 AMG
  {
    id: "veh-10",
    organizationId: "org-xmotion-1",
    plateDisplay: "45-MB-00",
    plateNormalized: "45MB00",
    vin: "WDD1770541J334455",
    make: "Mercedes-Benz",
    model: "A45 S AMG 4MATIC+",
    generationYear: 2023,
    bodyType: "hatchback",
    originalColorName: "Mountain Grey Magno",
    originalColorFamily: "grey",
    originalColorCode: "662",
    currentMileage: 21400,
    fuelType: "gasoline",
    notes: "PPF total com película mate e revisão periódica confirmada.",
    createdAt: "2026-02-14T09:30:00Z",
    updatedAt: "2026-08-10T11:00:00Z",
    currentOwner: {
      customerId: "c-part-7",
      customerName: "Marta Guimarães",
      customerType: "individual",
      since: "2026-02-14",
    },
  },
  // 11. Porsche Macan GTS
  {
    id: "veh-11",
    organizationId: "org-xmotion-1",
    plateDisplay: "77-PO-88",
    plateNormalized: "77PO88",
    vin: "WP1AB2A57PL556677",
    make: "Porsche",
    model: "Macan GTS",
    generationYear: 2023,
    bodyType: "suv",
    originalColorName: "Carmine Red",
    originalColorFamily: "red",
    originalColorCode: "0L",
    currentMileage: 16000,
    fuelType: "gasoline",
    notes: "Orçamento para proteção de óticas e pack frontal.",
    createdAt: "2026-08-24T10:00:00Z",
    updatedAt: "2026-08-24T10:00:00Z",
    currentOwner: {
      customerId: "c-part-10",
      customerName: "Inês Carvalho",
      customerType: "individual",
      since: "2026-08-24",
    },
  },
  // 12. Audi Q8 Sportback
  {
    id: "veh-12",
    organizationId: "org-xmotion-1",
    plateDisplay: "88-AQ-88",
    plateNormalized: "88AQ88",
    vin: "WAUZZZ4M3PD667788",
    make: "Audi",
    model: "Q8 55 TFSIe Sportback",
    generationYear: 2024,
    bodyType: "suv",
    originalColorName: "Daytona Grey Pearl",
    originalColorFamily: "grey",
    originalColorCode: "6Y",
    currentMileage: 7400,
    fuelType: "hybrid",
    notes: "PPF acetinado em toda a carroçaria com frisos em preto piano.",
    createdAt: "2026-05-12T13:45:00Z",
    updatedAt: "2026-08-18T15:00:00Z",
    currentOwner: {
      customerId: "c-part-12",
      customerName: "Helena Sousa",
      customerType: "individual",
      since: "2026-05-12",
    },
  },
  // 13. AutoStand Fleet Porsche Taycan
  {
    id: "veh-13",
    organizationId: "org-xmotion-1",
    plateDisplay: "01-TY-24",
    plateNormalized: "01TY24",
    vin: "WP0AA2Y14PSA11223",
    make: "Porsche",
    model: "Taycan 4S Cross Turismo",
    generationYear: 2024,
    bodyType: "wagon",
    originalColorName: "Neptune Blue",
    originalColorFamily: "blue",
    originalColorCode: "N5",
    currentMileage: 1200,
    fuelType: "electric",
    notes: "Viatura de demonstração AutoStand Prime. Full PPF com garantia de fábrica.",
    createdAt: "2026-07-15T09:00:00Z",
    updatedAt: "2026-08-22T14:00:00Z",
    currentOwner: {
      customerId: "c-b2b-1",
      customerName: "AutoStand Prime Barcelos",
      customerType: "business",
      since: "2026-07-15",
    },
  },
  // 14. AutoStand Fleet BMW i4 M50
  {
    id: "veh-14",
    organizationId: "org-xmotion-1",
    plateDisplay: "02-TY-24",
    plateNormalized: "02TY24",
    vin: "WBA33AW08PFP44556",
    make: "BMW",
    model: "i4 M50 Gran Coupe",
    generationYear: 2024,
    bodyType: "sedan",
    originalColorName: "Frozen Portimao Blue",
    originalColorFamily: "blue",
    originalColorCode: "C3Z",
    currentMileage: 2500,
    fuelType: "electric",
    notes: "Proteção PPF mate sobre pintura mate de fábrica.",
    createdAt: "2026-07-20T11:00:00Z",
    updatedAt: "2026-08-25T16:00:00Z",
    currentOwner: {
      customerId: "c-b2b-1",
      customerName: "AutoStand Prime Barcelos",
      customerType: "business",
      since: "2026-07-20",
    },
  },
  // 15. Apex Club Porsche GT3 RS
  {
    id: "veh-15",
    organizationId: "org-xmotion-1",
    plateDisplay: "99-GT-03",
    plateNormalized: "99GT03",
    vin: "WP0AB2A97PS998877",
    make: "Porsche",
    model: "911 GT3 RS (992)",
    generationYear: 2024,
    bodyType: "coupe",
    originalColorName: "Guards Red",
    originalColorFamily: "red",
    originalColorCode: "84A",
    currentMileage: 3100,
    fuelType: "gasoline",
    notes: "PPF ultra resistente a impactos de pista nos arcos de roda, difusor e capô em carbono exposto.",
    createdAt: "2026-03-15T10:00:00Z",
    updatedAt: "2026-08-12T17:00:00Z",
    currentOwner: {
      customerId: "c-b2b-2",
      customerName: "Apex Track & Club",
      customerType: "business",
      since: "2026-03-15",
    },
  },
  // 16. Apex Club McLaren 720S
  {
    id: "veh-16",
    organizationId: "org-xmotion-1",
    plateDisplay: "72-MC-00",
    plateNormalized: "72MC00",
    vin: "SBM11AAA6JW009988",
    make: "McLaren",
    model: "720S Spider",
    generationYear: 2022,
    bodyType: "cabrio",
    originalColorName: "Papaya Spark",
    originalColorFamily: "orange",
    originalColorCode: "MS-07",
    currentMileage: 9500,
    fuelType: "gasoline",
    notes: "Proteção frontal e retrovisores de carbono.",
    createdAt: "2026-05-01T14:00:00Z",
    updatedAt: "2026-08-01T11:00:00Z",
    currentOwner: {
      customerId: "c-b2b-2",
      customerName: "Apex Track & Club",
      customerType: "business",
      since: "2026-05-01",
    },
  },
  // 17. NorteDetail Mercedes C63 AMG
  {
    id: "veh-17",
    organizationId: "org-xmotion-1",
    plateDisplay: "63-AM-00",
    plateNormalized: "63AM00",
    vin: "WDD2050871F889900",
    make: "Mercedes-Benz",
    model: "C63 S AMG Coupe",
    generationYear: 2021,
    bodyType: "coupe",
    originalColorName: "Iridium Silver",
    originalColorFamily: "silver",
    originalColorCode: "775",
    currentMileage: 41000,
    fuelType: "gasoline",
    notes: "Chrome delete nas grelhas Panamericana e difusor.",
    createdAt: "2026-06-10T11:30:00Z",
    updatedAt: "2026-08-14T10:00:00Z",
    currentOwner: {
      customerId: "c-b2b-3",
      customerName: "NorteDetail Fleet",
      customerType: "business",
      since: "2026-06-10",
    },
  },
  // 18. AutoStand Fleet Audi RS3
  {
    id: "veh-18",
    organizationId: "org-xmotion-1",
    plateDisplay: "03-RS-24",
    plateNormalized: "03RS24",
    vin: "WAUZZZGY5PA123789",
    make: "Audi",
    model: "RS3 Sportback (8Y)",
    generationYear: 2024,
    bodyType: "hatchback",
    originalColorName: "Kyalami Green",
    originalColorFamily: "green",
    originalColorCode: "2K",
    currentMileage: 500,
    fuelType: "gasoline",
    notes: "Recém-chegado para orçamento de pack frontal e proteção de óticas.",
    createdAt: "2026-08-25T15:00:00Z",
    updatedAt: "2026-08-25T15:00:00Z",
    currentOwner: {
      customerId: "c-b2b-1",
      customerName: "AutoStand Prime Barcelos",
      customerType: "business",
      since: "2026-08-25",
    },
  },
];
