import { VisionAnalysis, FinishPreset } from "@/domains/intelligence/types";

export const initialVisionAnalyses: VisionAnalysis[] = [
  {
    id: "vis-1",
    vehiclePlate: "44-TX-88",
    vehicleMake: "BMW",
    vehicleModel: "M4 Competition Coupe (G82)",
    vehicleYear: 2024,
    originalColorName: "Isle of Man Green Metallic",
    originalColorFamily: "green",
    targetColorName: "Stek DYNOshield Gloss (Incolor)",
    targetColorFamily: "clear",
    serviceType: "PPF",
    contrastLevel: "low",
    recommendedCoverage: "exterior",
    photoCompleteness: true,
    vehicleConfidence: 0.98,
    colorConfidence: 0.95,
    createdAt: "2026-08-28 09:25",
    reviewedBy: "João Martins",
    reviewedAt: "2026-08-28 09:30",
    damageSuggestions: [
      {
        id: "vdmg-1",
        photoAngle: "front",
        bodyPart: "Para-choques Dianteiro (Grelha Inferior)",
        type: "stone_chip",
        severity: "minor",
        description: "2 micro picadas de gravilha superficial na entrada de ar direita.",
        boundingBox: { x: 22, y: 35, width: 14, height: 12 },
        confidence: 0.96,
        status: "confirmed",
      },
      {
        id: "vdmg-2",
        photoAngle: "right_side",
        bodyPart: "Bordo da Jante Traseira Direita",
        type: "scratch",
        severity: "minor",
        description: "Marcação superficial de aproximação ao passeio no verniz da jante.",
        boundingBox: { x: 74, y: 68, width: 10, height: 8 },
        confidence: 0.91,
        status: "confirmed",
      },
    ],
    panels: [
      {
        panelCode: "front_bumper",
        panelName: "Para-choques Dianteiro & Grelhas M",
        complexity: "high",
        estimatedMinutes: 270,
        disassemblyRecommended: ["Sensores de Estacionamento ADAS", "Emblema M4", "Grelhas Inferiores"],
        risks: ["Sensores de proximidade ultra-sensíveis", "Ângulos retos nas entradas de ar"],
        confidence: 0.97,
        status: "confirmed",
      },
      {
        panelCode: "hood",
        panelName: "Capô com Cavidades M",
        complexity: "medium",
        estimatedMinutes: 150,
        disassemblyRecommended: ["Emblema BMW Dianteiro", "Injetores de Limpa-vidros"],
        risks: ["Curvatura nas estrias do capô"],
        confidence: 0.98,
        status: "confirmed",
      },
      {
        panelCode: "roof",
        panelName: "Tejadilho em Carbono",
        complexity: "low",
        estimatedMinutes: 120,
        disassemblyRecommended: ["Antena Shark Fin"],
        risks: ["Superfície de verniz sobre carbono"],
        confidence: 0.99,
        status: "confirmed",
      },
      {
        panelCode: "doors",
        panelName: "Portas Laterais (2 Unidades)",
        complexity: "low",
        estimatedMinutes: 240,
        disassemblyRecommended: ["Puxadores das Portas", "Espelhos Retrovisores M"],
        risks: ["Fichas elétricas nos espelhos"],
        confidence: 0.98,
        status: "confirmed",
      },
    ],
    recommendedSequence: [
      "1. Desmontagem de puxadores e espelhos retrovisores",
      "2. Lavagem química e descontaminação com Clay Bar",
      "3. Aplicação do Tejadilho em Carbono",
      "4. Aplicação do Capô com cavidades M",
      "5. Aplicação das Portas e Guarda-lamas",
      "6. Aplicação do Para-choques Dianteiro",
      "7. Remontagem e pós-aquecimento a 90°C",
      "8. Controlo de Qualidade Scangrip (QC 10/10)",
    ],
  },
  {
    id: "vis-2",
    vehiclePlate: "99-PZ-11",
    vehicleMake: "Porsche",
    vehicleModel: "911 Carrera 4S (992)",
    vehicleYear: 2023,
    originalColorName: "GT Silver Metallic (Prata Claro)",
    originalColorFamily: "silver",
    targetColorName: "3M 2080 Satin Dark Grey (Cinza Escuro)",
    targetColorFamily: "dark_grey",
    serviceType: "Wrap",
    contrastLevel: "high",
    recommendedCoverage: "extended",
    photoCompleteness: true,
    vehicleConfidence: 0.97,
    colorConfidence: 0.94,
    createdAt: "2026-08-28 10:18",
    reviewedBy: "João Martins",
    damageSuggestions: [
      {
        id: "vdmg-3",
        photoAngle: "front",
        bodyPart: "Capô Central",
        type: "stone_chip",
        severity: "minor",
        description: "Micro picada de autoestrada no centro do capô.",
        boundingBox: { x: 50, y: 15, width: 8, height: 8 },
        confidence: 0.94,
        status: "confirmed",
      },
    ],
    panels: [
      {
        panelCode: "rear_hips",
        panelName: "Ancas Traseiras & Guarda-lamas Largos",
        complexity: "high",
        estimatedMinutes: 300,
        disassemblyRecommended: ["Óticas Traseiras LED", "Tampa do Depósito"],
        risks: ["Pré-estiramento elevado na curvatura das ancas"],
        confidence: 0.95,
        status: "confirmed",
      },
      {
        panelCode: "front_bumper",
        panelName: "Para-choques Dianteiro Aerodinâmico",
        complexity: "medium",
        estimatedMinutes: 240,
        disassemblyRecommended: ["Grelhas Ativas de Refrigeração"],
        risks: ["Flaps móveis eletrónicos"],
        confidence: 0.96,
        status: "confirmed",
      },
    ],
    recommendedSequence: [
      "1. Desmontagem de óticas traseiras e puxadores",
      "2. Descontaminação com álcool isopropílico IPA",
      "3. Aplicação do Tejadilho e Capô",
      "4. Moldagem das Ancas Traseiras com estiramento a quente",
      "5. Portas e Para-choques Dianteiro",
      "6. Acabamentos de soleiras para cobertura do contraste prata/escuro",
      "7. Cura térmica a 90°C",
      "8. Inspeção Final QC",
    ],
  },
];

export const initialFinishPresets: FinishPreset[] = [
  {
    id: "fin-1",
    name: "Stek DYNOshield Gloss",
    brand: "Stek Automotive",
    type: "clear_ppf_gloss",
    colorHex: "#1a1e20",
    textureEffect: "gloss",
    costPerMeterCents: 4200,
    warrantyYears: 10,
  },
  {
    id: "fin-2",
    name: "Stek DYNOmatte Satin",
    brand: "Stek Automotive",
    type: "clear_ppf_matte",
    colorHex: "#282d30",
    textureEffect: "satin",
    costPerMeterCents: 4800,
    warrantyYears: 10,
  },
  {
    id: "fin-3",
    name: "3M 2080 Satin Dark Grey",
    brand: "3M Wrap Film Series",
    type: "vinyl_wrap",
    colorHex: "#373a3c",
    textureEffect: "satin",
    costPerMeterCents: 2800,
    warrantyYears: 7,
  },
  {
    id: "fin-4",
    name: "Avery Dennison Nardo Grey",
    brand: "Avery Supreme Wrapping",
    type: "vinyl_wrap",
    colorHex: "#70767c",
    textureEffect: "gloss",
    costPerMeterCents: 2950,
    warrantyYears: 7,
  },
  {
    id: "fin-5",
    name: "Inozetek Frozen Black Metallic",
    brand: "Inozetek Supergloss",
    type: "color_ppf",
    colorHex: "#111314",
    textureEffect: "matte",
    costPerMeterCents: 5500,
    warrantyYears: 8,
  },
  {
    id: "fin-6",
    name: "Shadowline Gloss Black (Chrome Delete)",
    brand: "3M 2080 Gloss",
    type: "chrome_delete",
    colorHex: "#08090a",
    textureEffect: "gloss",
    costPerMeterCents: 1800,
    warrantyYears: 5,
  },
];
