import { WorkOrder } from "@/domains/checkins/types";

export const initialWorkOrdersData: WorkOrder[] = [
  {
    id: "wo-1",
    organizationId: "org-xmotion-1",
    workOrderNumber: "OT-2026-042",
    vehicleId: "veh-1",
    vehiclePlate: "44-TX-88",
    vehicleModel: "BMW M4 Competition Coupe",
    customerId: "c-b2b-1",
    customerName: "AutoStand Prime Barcelos",
    checkinId: "chk-1",
    status: "in_progress",
    serviceTitle: "Proteção Integral PPF Auto-regenerativo",
    primaryTechnicianName: "João Martins",
    progressPercentage: 65,
    estimatedHours: 8.5,
    actualHoursSpent: 5.5,
    startedAt: "2026-08-28 09:30",
  },
  {
    id: "wo-2",
    organizationId: "org-xmotion-1",
    workOrderNumber: "OT-2026-040",
    vehicleId: "veh-2",
    vehiclePlate: "99-PZ-11",
    vehicleModel: "Porsche 911 Carrera 4S (992)",
    customerId: "c-part-1",
    customerName: "Bernardo Silva",
    checkinId: "chk-2",
    status: "in_progress",
    serviceTitle: "Full Body Wrap Satin Grey",
    primaryTechnicianName: "Rui Almeida",
    progressPercentage: 40,
    estimatedHours: 7.5,
    actualHoursSpent: 3.0,
    startedAt: "2026-08-28 10:30",
  },
  {
    id: "wo-3",
    organizationId: "org-xmotion-1",
    workOrderNumber: "OT-2026-039",
    vehicleId: "veh-3",
    vehiclePlate: "12-RS-66",
    vehicleModel: "Audi RS6 Avant V8 BiTurbo",
    customerId: "c-part-3",
    customerName: "Tiago Cerqueira",
    checkinId: "chk-3",
    status: "in_progress",
    serviceTitle: "PPF Frontal Completo & Cerâmica de Jantes",
    primaryTechnicianName: "Pedro Santos",
    progressPercentage: 75,
    estimatedHours: 6.0,
    actualHoursSpent: 4.5,
    startedAt: "2026-08-28 12:30",
  },
  {
    id: "wo-4",
    organizationId: "org-xmotion-1",
    workOrderNumber: "OT-2026-037",
    vehicleId: "veh-4",
    vehiclePlate: "78-MB-22",
    vehicleModel: "Mercedes GLC Coupe 300d",
    customerId: "c-part-2",
    customerName: "Miguel Ângelo Costa",
    checkinId: "chk-4",
    status: "waiting_parts",
    serviceTitle: "Chrome Delete Integral & Grelha Panamericana",
    primaryTechnicianName: "Miguel Costa",
    progressPercentage: 20,
    estimatedHours: 4.0,
    actualHoursSpent: 1.0,
    startedAt: "2026-08-28 14:15",
  },
];
